package yj.core.ztpp0023.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable=true)
@Table(name = "sap_ztpp0023")
public class Ztpp0023 extends BaseDTO {
     @NotEmpty
      private String qdwerk; //工厂

     @NotEmpty
      private String qaufnr; //机加生产订单

     @Id
     @GeneratedValue
      private String yaufnr; //压铸生产订单

      private String qdauat; //机加订单类型

      private String qmatnr; //机加物料

      private String qfevor; //机加车间

      private Double qgamng; //机加数量

      private Double menge; //转换数量

      private String ydauat; //压铸订单类型

      private String ymatnr; //毛坯物料

      private String yfevor; //压铸车间

      private String yverid; //压铸生产版本

      private String ygstrp; //压铸开始日期

      private String ygltrp; //压铸结束日期

      private Double ygamng; //压铸数量

      private String attr1;

      private String attr2;

      private String attr3;

      private String attr4;

      private String attr5;

      private String attr6;

      private String attr7;


     public void setQdwerk(String qdwerk){
         this.qdwerk = qdwerk;
     }

     public String getQdwerk(){
         return qdwerk;
     }

     public void setQaufnr(String qaufnr){
         this.qaufnr = qaufnr;
     }

     public String getQaufnr(){
         return qaufnr;
     }

     public void setYaufnr(String yaufnr){
         this.yaufnr = yaufnr;
     }

     public String getYaufnr(){
         return yaufnr;
     }

     public void setQdauat(String qdauat){
         this.qdauat = qdauat;
     }

     public String getQdauat(){
         return qdauat;
     }

     public void setQmatnr(String qmatnr){
         this.qmatnr = qmatnr;
     }

     public String getQmatnr(){
         return qmatnr;
     }

     public void setQfevor(String qfevor){
         this.qfevor = qfevor;
     }

     public String getQfevor(){
         return qfevor;
     }

     public void setQgamng(Double qgamng){
         this.qgamng = qgamng;
     }

     public Double getQgamng(){
         return qgamng;
     }

     public void setMenge(Double menge){
         this.menge = menge;
     }

     public Double getMenge(){
         return menge;
     }

     public void setYdauat(String ydauat){
         this.ydauat = ydauat;
     }

     public String getYdauat(){
         return ydauat;
     }

     public void setYmatnr(String ymatnr){
         this.ymatnr = ymatnr;
     }

     public String getYmatnr(){
         return ymatnr;
     }

     public void setYfevor(String yfevor){
         this.yfevor = yfevor;
     }

     public String getYfevor(){
         return yfevor;
     }

     public void setYverid(String yverid){
         this.yverid = yverid;
     }

     public String getYverid(){
         return yverid;
     }

     public void setYgstrp(String ygstrp){
         this.ygstrp = ygstrp;
     }

     public String getYgstrp(){
         return ygstrp;
     }

     public void setYgltrp(String ygltrp){
         this.ygltrp = ygltrp;
     }

     public String getYgltrp(){
         return ygltrp;
     }

     public void setYgamng(Double ygamng){
         this.ygamng = ygamng;
     }

     public Double getYgamng(){
         return ygamng;
     }

     public void setAttr1(String attr1){
         this.attr1 = attr1;
     }

     public String getAttr1(){
         return attr1;
     }

     public void setAttr2(String attr2){
         this.attr2 = attr2;
     }

     public String getAttr2(){
         return attr2;
     }

     public void setAttr3(String attr3){
         this.attr3 = attr3;
     }

     public String getAttr3(){
         return attr3;
     }

     public void setAttr4(String attr4){
         this.attr4 = attr4;
     }

     public String getAttr4(){
         return attr4;
     }

     public void setAttr5(String attr5){
         this.attr5 = attr5;
     }

     public String getAttr5(){
         return attr5;
     }

     public void setAttr6(String attr6){
         this.attr6 = attr6;
     }

     public String getAttr6(){
         return attr6;
     }

     public void setAttr7(String attr7){
         this.attr7 = attr7;
     }

     public String getAttr7(){
         return attr7;
     }

     }
