package yj.core.dispatch.dto;


/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "confirmation_log")
public class Log extends BaseDTO {
     @Id
     @GeneratedValue
      private Long id;

      private String tranType; //事物类型：报工/冲销

      private Long refId; //参考ID

      private String msgty; //消息类型

      private String msgtx; //消息内容

      private String created_by;

      @Transient
      private Date creationDate;

      private Date lastUpdateDate;

    public String getCreated_by() {
        return created_by;
    }

    public void setCreated_by(String created_by) {
        this.created_by = created_by;
    }

    public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setTranType(String tranType){
         this.tranType = tranType;
     }

     public String getTranType(){
         return tranType;
     }

     public void setRefId(Long refId){
         this.refId = refId;
     }

     public Long getRefId(){
         return refId;
     }

     public void setMsgty(String msgty){
         this.msgty = msgty;
     }

     public String getMsgty(){
         return msgty;
     }

     public void setMsgtx(String msgtx){
         this.msgtx = msgtx;
     }

     public String getMsgtx(){
         return msgtx;
     }

    @Override
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    @Override
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    @Override
    public Date getCreationDate() {
        return creationDate;
    }

    @Override
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
}
