package yj.core.imfpmrecheckplan.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable=true)
@Table(name = "imf_pm_recheckplan")
public class Recheckplan extends BaseDTO {
    @Id
    private String checkdoc;//点检凭证

    private String mpobj;//设备编号

    private String point;//计量点

    private String checkdate;//点检日期

    private String checktime;//点检时间

    private String checkshift;//点检班次

    private String checkuser;//点检人

    private String codct;//目录:常量：Z

    private String codgr;// 代码组

    private String kurztext1;//代码组文本

    private String code;//代码

    private String kurztext2;//代码文本

    private String atinn;//内部特性号(特征编号）:该字段需转换，未转换前是10位数字格式

    private String atbez;//特性描述

    private Float readg;//计量读数

    private Float mrmin;//范围下限:这个字段是科学计数，转换为10进制计数后需要除以100

    private Float mrmax;//范围上限:这个字段是科学计数，转换为10进制计数后需要除以100

    private Integer mrngu;//计量范围单位

    private String mdtxt;//处理说明

    private String recheckState;//复检标记：N：表示未复检，默认为N；Y：表示复检完成

    private String recheckdate;//复检日期

    private String rechecktime;//复检时间

    private String recheckshift;//复检班次

    private String recheckuser;//复检人

    private String recheckdoc;//复检凭证

    public String getCheckdoc() {
        return checkdoc;
    }

    public void setCheckdoc(String checkdoc) {
        this.checkdoc = checkdoc;
    }

    public String getMpobj() {
        return mpobj;
    }

    public void setMpobj(String mpobj) {
        this.mpobj = mpobj;
    }

    public String getPoint() {
        return point;
    }

    public void setPoint(String point) {
        this.point = point;
    }

    public String getCheckdate() {
        return checkdate;
    }

    public void setCheckdate(String checkdate) {
        this.checkdate = checkdate;
    }

    public String getChecktime() {
        return checktime;
    }

    public void setChecktime(String checktime) {
        this.checktime = checktime;
    }

    public String getCheckshift() {
        return checkshift;
    }

    public void setCheckshift(String checkshift) {
        this.checkshift = checkshift;
    }

    public String getCheckuser() {
        return checkuser;
    }

    public void setCheckuser(String checkuser) {
        this.checkuser = checkuser;
    }

    public String getCodct() {
        return codct;
    }

    public void setCodct(String codct) {
        this.codct = codct;
    }

    public String getCodgr() {
        return codgr;
    }

    public void setCodgr(String codgr) {
        this.codgr = codgr;
    }

    public String getKurztext1() {
        return kurztext1;
    }

    public void setKurztext1(String kurztext1) {
        this.kurztext1 = kurztext1;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getKurztext2() {
        return kurztext2;
    }

    public void setKurztext2(String kurztext2) {
        this.kurztext2 = kurztext2;
    }

    public String getAtinn() {
        return atinn;
    }

    public void setAtinn(String atinn) {
        this.atinn = atinn;
    }

    public String getAtbez() {
        return atbez;
    }

    public void setAtbez(String atbez) {
        this.atbez = atbez;
    }

    public Float getReadg() {
        return readg;
    }

    public void setReadg(Float readg) {
        this.readg = readg;
    }

    public Float getMrmin() {
        return mrmin;
    }

    public void setMrmin(Float mrmin) {
        this.mrmin = mrmin;
    }

    public Float getMrmax() {
        return mrmax;
    }

    public void setMrmax(Float mrmax) {
        this.mrmax = mrmax;
    }

    public Integer getMrngu() {
        return mrngu;
    }

    public void setMrngu(Integer mrngu) {
        this.mrngu = mrngu;
    }

    public String getMdtxt() {
        return mdtxt;
    }

    public void setMdtxt(String mdtxt) {
        this.mdtxt = mdtxt;
    }

    public String getRecheckState() {
        return recheckState;
    }

    public void setRecheckState(String recheckState) {
        this.recheckState = recheckState;
    }

    public String getRecheckdate() {
        return recheckdate;
    }

    public void setRecheckdate(String recheckdate) {
        this.recheckdate = recheckdate;
    }

    public String getRechecktime() {
        return rechecktime;
    }

    public void setRechecktime(String rechecktime) {
        this.rechecktime = rechecktime;
    }

    public String getRecheckshift() {
        return recheckshift;
    }

    public void setRecheckshift(String recheckshift) {
        this.recheckshift = recheckshift;
    }

    public String getRecheckuser() {
        return recheckuser;
    }

    public void setRecheckuser(String recheckuser) {
        this.recheckuser = recheckuser;
    }

    public String getRecheckdoc() {
        return recheckdoc;
    }

    public void setRecheckdoc(String recheckdoc) {
        this.recheckdoc = recheckdoc;
    }
}
