package yj.core.assyassign.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "wip_assyassign")
public class Assyassign extends BaseDTO {
     @Id
     @GeneratedValue
      private String zsxjlh; //毛坯上线GUID号

     @NotEmpty
      private String assyId; //装配件上线记录号

      private String operationCode; //工序代码

      private String vornr; //工序

      private String zxhbar; //箱条码号

      private String lifnr; //供应商

      private String sortl; //供应商简称

      private Date lifnrDate; //供应商生产日期

      private String lifnrLotn; //供应商批号

      private String charg; //库存批次

      private String matnr; //BOM组件料号

      private String zgjbar; //工件二维码

      private String zmpbar; //毛坯二维码

      private String lineId; //产线ID

      private String matnr2; //成品物料

      private Double allocQty; //分配数量

      private String gmein; //单位

      private String lgort; //库存地点

      private Double zsxnum; //上线数量

      private String status; //状态

      private Double unitqty; //BOM标准用量


     public void setZsxjlh(String zsxjlh){
         this.zsxjlh = zsxjlh;
     }

     public String getZsxjlh(){
         return zsxjlh;
     }

     public void setAssyId(String assyId){
         this.assyId = assyId;
     }

     public String getAssyId(){
         return assyId;
     }

     public void setOperationCode(String operationCode){
         this.operationCode = operationCode;
     }

     public String getOperationCode(){
         return operationCode;
     }

     public void setVornr(String vornr){
         this.vornr = vornr;
     }

     public String getVornr(){
         return vornr;
     }

     public void setZxhbar(String zxhbar){
         this.zxhbar = zxhbar;
     }

     public String getZxhbar(){
         return zxhbar;
     }

     public void setLifnr(String lifnr){
         this.lifnr = lifnr;
     }

     public String getLifnr(){
         return lifnr;
     }

     public void setSortl(String sortl){
         this.sortl = sortl;
     }

     public String getSortl(){
         return sortl;
     }

     public void setLifnrDate(Date lifnrDate){
         this.lifnrDate = lifnrDate;
     }

     public Date getLifnrDate(){
         return lifnrDate;
     }

     public void setLifnrLotn(String lifnrLotn){
         this.lifnrLotn = lifnrLotn;
     }

     public String getLifnrLotn(){
         return lifnrLotn;
     }

     public void setCharg(String charg){
         this.charg = charg;
     }

     public String getCharg(){
         return charg;
     }

     public void setMatnr(String matnr){
         this.matnr = matnr;
     }

     public String getMatnr(){
         return matnr;
     }

     public void setZgjbar(String zgjbar){
         this.zgjbar = zgjbar;
     }

     public String getZgjbar(){
         return zgjbar;
     }

     public void setZmpbar(String zmpbar){
         this.zmpbar = zmpbar;
     }

     public String getZmpbar(){
         return zmpbar;
     }

     public void setLineId(String lineId){
         this.lineId = lineId;
     }

     public String getLineId(){
         return lineId;
     }

     public void setMatnr2(String matnr2){
         this.matnr2 = matnr2;
     }

     public String getMatnr2(){
         return matnr2;
     }

     public void setAllocQty(Double allocQty){
         this.allocQty = allocQty;
     }

     public Double getAllocQty(){
         return allocQty;
     }

     public void setGmein(String gmein){
         this.gmein = gmein;
     }

     public String getGmein(){
         return gmein;
     }

     public void setLgort(String lgort){
         this.lgort = lgort;
     }

     public String getLgort(){
         return lgort;
     }

     public void setZsxnum(Double zsxnum){
         this.zsxnum = zsxnum;
     }

     public Double getZsxnum(){
         return zsxnum;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     public void setUnitqty(Double unitqty){
         this.unitqty = unitqty;
     }

     public Double getUnitqty(){
         return unitqty;
     }

     }
