# Default values for api-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.choerodon.com.cn/hap-framework/hap-framework
  pullPolicy: Always

service:
  enable: false
  type: ClusterIP
  port: 80
  name: hap-framework

ingress:
  enable: false
  host: choerodon.com.cn

env:
  open:
    MYSQL_HOST: 127.0.0.1
    MYSQL_PORT: 3306
    MYSQL_DB: hap_dev
    MYSQL_USER: hap_dev
    MYSQL_PASS: hap_dev
    REDIS_IP: 127.0.0.1
    REDIS_DB: 6379


logs:
  parser: spring-boot

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
    # cpu: 100m
    memory: 2Gi
  requests:
    # cpu: 100m
    memory: 1Gi
