package yj.core.webservice_queryXhcard.sender;


import yj.core.webservice_queryXhcard.receiver.DTQUERYXHCARDRes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 *
 */
@WebService(name = "SI_QUERYXHCARD_Sender_Syn", targetNamespace = "http://www.cq-yj.com/HAP/queryXhcard/Sender")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIQUERYXHCARDSenderSyn {

    /**
     *
     * @param mtQUERYXHCARDReq
     * @return returns com.cq_yj.hap.queryxhcard.sender.DTQUERYXHCARDRes
     */
    @WebMethod(operationName = "SI_QUERYXHCARD_Sender_Syn", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_QUERYXHCARD_Res", targetNamespace = "http://www.cq-yj.com/HAP/queryXhcard/Sender", partName = "MT_QUERYXHCARD_Res")
    public DTQUERYXHCARDRes siQUERYXHCARDSenderSyn(
            @WebParam(name = "MT_QUERYXHCARD_Req", targetNamespace = "http://www.cq-yj.com/HAP/queryXhcard/Sender", partName = "MT_QUERYXHCARD_Req") DTQUERYXHCARDReq mtQUERYXHCARDReq);

}
