package yj.core.webservice_queryXhcard.sender;


import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 *
 * <pre>
 * SI_QUERYXHCARD_Sender_SynService service = new SI_QUERYXHCARD_Sender_SynService();
 * SIQUERYXHCARDSenderSyn portType = service.getHTTPPort();
 * portType.siQUERYXHCARDSenderSyn(...);
 * </pre>
 *
 * </p>
 *
 */
@WebServiceClient(name = "SI_QUERYXHCARD_Sender_SynService", targetNamespace = "http://www.cq-yj.com/HAP/queryXhcard/Sender", wsdlLocation = "resources/queryXhcard.xml")
public class SIQUERYXHCARDSenderSynService extends Service {

    public final static URL WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(SIQUERYXHCARDSenderSynService.class.getName());

    static {
        URL url = null;
        url = SIQUERYXHCARDSenderSynService.class.getClassLoader().getResource("queryXhcard.xml");
        System.out.println(url);
        WSDL_LOCATION = url;
    }

    public SIQUERYXHCARDSenderSynService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIQUERYXHCARDSenderSynService() {
        super(WSDL_LOCATION, new QName(
                "http://www.cq-yj.com/HAP/queryXhcard/Sender",
                "SI_QUERYXHCARD_Sender_SynService"));
    }

    /**
     *
     * @return returns SIQUERYXHCARDSenderSyn
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIQUERYXHCARDSenderSyn getHTTPPort() {
        return super.getPort(new QName(
                        "http://www.cq-yj.com/HAP/queryXhcard/Sender", "HTTP_Port"),
                SIQUERYXHCARDSenderSyn.class);
    }

    /**
     *
     * @return returns SIQUERYXHCARDSenderSyn
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIQUERYXHCARDSenderSyn getHTTPSPort() {
        return super.getPort(new QName(
                        "http://www.cq-yj.com/HAP/queryXhcard/Sender", "HTTPS_Port"),
                SIQUERYXHCARDSenderSyn.class);
    }

}

