package yj.core.webserver_readtp.sender;

/**
 * Created by 917110140 on 2018/10/6.
 */


import yj.core.webserver_readtp.receiver.DTREADTPRes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 *
 */
@WebService(name = "SI_READTP_Sender_Syn", targetNamespace = "http://www.cq-yj.com/HAP/READTP/Sender")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIREADTPSenderSyn {

    /**
     *
     * @param mtREADTPReq
     * @return returns com.cq_yj.hap.readtp.sender.DTREADTPRes
     */
    @WebMethod(operationName = "SI_READTP_Sender_Syn", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_READTP_Res", targetNamespace = "http://www.cq-yj.com/HAP/READTP/Sender", partName = "MT_READTP_Res")
    public DTREADTPRes siREADTPSenderSyn(
            @WebParam(name = "MT_READTP_Req", targetNamespace = "http://www.cq-yj.com/HAP/READTP/Sender", partName = "MT_READTP_Req") DTREADTPReq mtREADTPReq);

}
