package yj.core.webserver_readtp.sender;

/**
 * Created by 917110140 on 2018/10/6.
 */

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 *
 * <pre>
 * SI_READTP_Sender_SynService service = new SI_READTP_Sender_SynService();
 * SIREADTPSenderSyn portType = service.getHTTPPort();
 * portType.siREADTPSenderSyn(...);
 * </pre>
 *
 * </p>
 *
 */
@WebServiceClient(name = "SI_READTP_Sender_SynService", targetNamespace = "http://www.cq-yj.com/HAP/READTP/Sender", wsdlLocation = "resources/readTp.xml")
public class SIREADTPSenderSynService extends Service {

    public final static URL WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(SIREADTPSenderSynService.class.getName());

    static {
        URL url = null;
        url = SIREADTPSenderSynService.class.getClassLoader().getResource("readTp.xml");
        System.out.println(url);
        WSDL_LOCATION = url;
    }

    public SIREADTPSenderSynService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIREADTPSenderSynService() {
        super(WSDL_LOCATION, new QName(
                "http://www.cq-yj.com/HAP/READTP/Sender",
                "SI_READTP_Sender_SynService"));
    }

    /**
     *
     * @return returns SIREADTPSenderSyn
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIREADTPSenderSyn getHTTPPort() {
        return super.getPort(new QName(
                        "http://www.cq-yj.com/HAP/READTP/Sender", "HTTP_Port"),
                SIREADTPSenderSyn.class);
    }

    /**
     *
     * @return returns SIREADTPSenderSyn
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIREADTPSenderSyn getHTTPSPort() {
        return super.getPort(new QName(
                        "http://www.cq-yj.com/HAP/READTP/Sender", "HTTPS_Port"),
                SIREADTPSenderSyn.class);
    }

}

