package yj.core.webserver_weidu.sender;

/**
 * Created by 917110140 on 2018/9/29.
 */

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 *
 * <pre>
 * SI_WEIDU_Sender_SynService service = new SI_WEIDU_Sender_SynService();
 * SIWEIDUSenderSyn portType = service.getHTTPPort();
 * portType.siWEIDUSenderSyn(...);
 * </pre>
 *
 * </p>
 *
 */
@WebServiceClient(name = "SI_WEIDU_Sender_SynService", targetNamespace = "http://www.cq-yj.com/HAP/WEIDU/Sender", wsdlLocation = "resources/weidu.xml")
public class SIWEIDUSenderSynService extends Service {

    public final static URL WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(SIWEIDUSenderSynService.class.getName());

    static {
        URL url = null;
        url = SIWEIDUSenderSynService.class.getClassLoader().getResource("weidu.xml");
        System.out.println(url);
        WSDL_LOCATION = url;
    }

    public SIWEIDUSenderSynService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIWEIDUSenderSynService() {
        super(WSDL_LOCATION, new QName(
                "http://www.cq-yj.com/HAP/WEIDU/Sender",
                "SI_WEIDU_Sender_SynService"));
    }

    /**
     *
     * @return returns SIWEIDUSenderSyn
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIWEIDUSenderSyn getHTTPPort() {
        return super.getPort(new QName("http://www.cq-yj.com/HAP/WEIDU/Sender",
                "HTTP_Port"), SIWEIDUSenderSyn.class);
    }

    /**
     *
     * @return returns SIWEIDUSenderSyn
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIWEIDUSenderSyn getHTTPSPort() {
        return super.getPort(new QName("http://www.cq-yj.com/HAP/WEIDU/Sender",
                "HTTPS_Port"), SIWEIDUSenderSyn.class);
    }

}

