package yj.core.webservice_xhcard.sender;

import yj.core.webservice_xhcard.receiver.DTXHCARDSENDXRES;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 *
 */
@WebService(name = "SI_XHCARD_SENDX_SYNC", targetNamespace = "http://www.cq-yj.com/HAP/PP001/xhcardSender")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIXHCARDSENDXSYNC {

    /**
     *
     * @param mtXHCARDSENDXREQ
     * @return returns com.cq_yj.hap.pp001.xhcardsender.DTXHCARDSENDXRES
     *
     */
    @WebMethod(operationName = "SI_XHCARD_SENDX_SYNC", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_XHCARD_SENDX_RES", targetNamespace = "http://www.cq-yj.com/HAP/PP001/xhcardSender", partName = "MT_XHCARD_SENDX_RES")
    public DTXHCARDSENDXRES siXHCARDSENDXSYNC(
            @WebParam(name = "MT_XHCARD_SENDX_REQ", targetNamespace = "http://www.cq-yj.com/HAP/PP001/xhcardSender", partName = "MT_XHCARD_SENDX_REQ") DTXHCARDSENDXREQ mtXHCARDSENDXREQ);


}
