package yj.core.webservice_xhcard.sender;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 *
 * <pre>
 * SI_XHCARD_SENDX_SYNCService service = new SI_XHCARD_SENDX_SYNCService();
 * SIXHCARDSENDXSYNC portType = service.getHTTPPort();
 * portType.siXHCARDSENDXSYNC(...);
 * </pre>
 *
 * </p>
 *
 */
@WebServiceClient(name = "SI_XHCARD_SENDX_SYNCService", targetNamespace = "http://www.cq-yj.com/HAP/PP001/xhcardSender", wsdlLocation = "resources/XHCARDwsdl.xml")
public class SIXHCARDSENDXSYNCService extends Service {

    public final static URL WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(SIXHCARDSENDXSYNCService.class.getName());
    static {
        URL url = null;
        url = SIXHCARDSENDXSYNCService.class.getClassLoader().getResource("XHCARDwsdl.xml");
        System.out.println(url);
        WSDL_LOCATION = url;
    }

    public SIXHCARDSENDXSYNCService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIXHCARDSENDXSYNCService() {
        super(WSDL_LOCATION, new QName(
                "http://www.cq-yj.com/HAP/PP001/xhcardSender",
                "SI_XHCARD_SENDX_SYNCService"));
    }

    /**
     *
     * @return returns SIXHCARDSENDXSYNC
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIXHCARDSENDXSYNC getHTTPPort() {
        return super.getPort(new QName(
                        "http://www.cq-yj.com/HAP/PP001/xhcardSender", "HTTP_Port"),
                SIXHCARDSENDXSYNC.class);
    }

    /**
     *
     * @return returns SIXHCARDSENDXSYNC
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIXHCARDSENDXSYNC getHTTPSPort() {
        return super.getPort(new QName(
                        "http://www.cq-yj.com/HAP/PP001/xhcardSender", "HTTPS_Port"),
                SIXHCARDSENDXSYNC.class);
    }

}
