package yj.core.shiftstime.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "sap_shiftstime")
public class Shiftstime extends BaseDTO {
    @Id
    @GeneratedValue
    private String werks;//工厂
    @NotNull
    private String shifts;//班次
    @NotNull
    private String type;//类型

    private String startTime;//班次开始时间

    private String endTime;//班次结束时间

    private String bgsTime;//报工开始时间

    private String bgeTime;//报工结束时间

    private String zsTime;//转班日开始时间

    private String zeTime;//转班日结束时间

    private String zbgsTime;//转班日报工开始时间

    private String zbgeTime;//转班日报工结束时间

    private String txt;//班次说明

    private Date creationDate; //创建时间
    private Long createdBy; //创建人
    private Date lastUpdateDate; //更新时间
    private Long lastUpdatedBy; //更新人

    public String getWerks() {
        return werks;
    }

    public void setWerks(String werks) {
        this.werks = werks;
    }

    public String getShifts() {
        return shifts;
    }

    public void setShifts(String shifts) {
        this.shifts = shifts;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    public String getBgsTime() {
        return bgsTime;
    }

    public void setBgsTime(String bgsTime) {
        this.bgsTime = bgsTime;
    }

    public String getBgeTime() {
        return bgeTime;
    }

    public void setBgeTime(String bgeTime) {
        this.bgeTime = bgeTime;
    }

    public String getZsTime() {
        return zsTime;
    }

    public void setZsTime(String zsTime) {
        this.zsTime = zsTime;
    }

    public String getZeTime() {
        return zeTime;
    }

    public void setZeTime(String zeTime) {
        this.zeTime = zeTime;
    }

    public String getZbgsTime() {
        return zbgsTime;
    }

    public void setZbgsTime(String zbgsTime) {
        this.zbgsTime = zbgsTime;
    }

    public String getZbgeTime() {
        return zbgeTime;
    }

    public void setZbgeTime(String zbgeTime) {
        this.zbgeTime = zbgeTime;
    }

    public String getTxt() {
        return txt;
    }

    public void setTxt(String txt) {
        this.txt = txt;
    }

    @Override
    public Date getCreationDate() {
        return creationDate;
    }

    @Override
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Override
    public Long getCreatedBy() {
        return createdBy;
    }

    @Override
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    @Override
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    @Override
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    @Override
    public Long getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    @Override
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
}
