package yj.core.qpcd.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable=true)
@Table(name = "sap_qpcd")
public class Qpcd extends BaseDTO {
     @NotEmpty
      private String mandt; //集团

     @NotEmpty
      private String katalogart; //目录

     @NotEmpty
      private String codegruppe; //缺陷代码组

     @NotEmpty
      private String code; //缺陷代码

     @Id
     @GeneratedValue
      private String version; //版本

     @NotEmpty
      private String kurztext; //缺陷代码短文本

     @NotEmpty
      private String status; //缺陷代码组状态

     @NotEmpty
      private String gkurztext; //缺陷代码组短文本


     public void setMandt(String mandt){
         this.mandt = mandt;
     }

     public String getMandt(){
         return mandt;
     }

     public void setKatalogart(String katalogart){
         this.katalogart = katalogart;
     }

     public String getKatalogart(){
         return katalogart;
     }

     public void setCodegruppe(String codegruppe){
         this.codegruppe = codegruppe;
     }

     public String getCodegruppe(){
         return codegruppe;
     }

     public void setCode(String code){
         this.code = code;
     }

     public String getCode(){
         return code;
     }

     public void setVersion(String version){
         this.version = version;
     }

     public String getVersion(){
         return version;
     }

     public void setKurztext(String kurztext){
         this.kurztext = kurztext;
     }

     public String getKurztext(){
         return kurztext;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     public void setGkurztext(String gkurztext){
         this.gkurztext = gkurztext;
     }

     public String getGkurztext(){
         return gkurztext;
     }

     }
