package yj.core.werbserver_crhd.sender;

import yj.core.werbserver_crhd.receiver.DTZZ002Res;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SI_ZZ002_Sender_Syn", targetNamespace = "http://www.cq-yj.com/HAP/PP001/SAP_CRHD/Sender")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIZZ002SenderSyn {

	/**
	 * 
	 * @param mtZZ002Req
	 * @return returns com.cq_yj.hap.pp001.sap_crhd.sender.DTZZ002Res
	 */
	@WebMethod(operationName = "SI_ZZ002_Sender_Syn", action = "http://sap.com/xi/WebService/soap1.1")
	@WebResult(name = "MT_ZZ002_Res", targetNamespace = "http://www.cq-yj.com/HAP/PP001/SAP_CRHD/Sender", partName = "MT_ZZ002_Res")
	public DTZZ002Res siZZ002SenderSyn(
            @WebParam(name = "MT_ZZ002_Req", targetNamespace = "http://www.cq-yj.com/HAP/PP001/SAP_CRHD/Sender", partName = "MT_ZZ002_Req") DTZZ002Req mtZZ002Req);

}
