package yj.core.zudlog.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "wip_zudlog")
public class Zudlog extends BaseDTO {
     @Id
     @GeneratedValue
      private String id;

      private String zudnum;

      private String item;

      private String status; //处理成功 1 处理失败 2

      private Long inputlogid;

      private String msgtx;
    @Transient
      private Date creationDate;

      private Long createdBy;

      private String createdBy1;
      private String creationDate1;

    public String getCreatedBy1() {
        return createdBy1;
    }

    public void setCreatedBy1(String createdBy1) {
        this.createdBy1 = createdBy1;
    }

    public String getCreationDate1() {
        return creationDate1;
    }

    public void setCreationDate1(String creationDate1) {
        this.creationDate1 = creationDate1;
    }

    public String getMsgtx() {
        return msgtx;
    }

    public void setMsgtx(String msgtx) {
        this.msgtx = msgtx;
    }

    public Long getInputlogid() {
        return inputlogid;
    }

    public void setInputlogid(Long inputlogid) {
        this.inputlogid = inputlogid;
    }

    public void setId(String id){
         this.id = id;
     }

     public String getId(){
         return id;
     }

     public void setZudnum(String zudnum){
         this.zudnum = zudnum;
     }

     public String getZudnum(){
         return zudnum;
     }

     public void setItem(String item){
         this.item = item;
     }

     public String getItem(){
         return item;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

    @Override
    public Date getCreationDate() {
        return creationDate;
    }

    @Override
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Override
    public Long getCreatedBy() {
        return createdBy;
    }

    @Override
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
}
