package yj.core.pmimptt.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable=true)
@Table(name = "sap_pm_imptt")
public class Imptt extends BaseDTO {
    @Id
    private String point;//计量点
    @Id
    private String mpobj;//设备编号

    private String pttxt;//计量点描述

    private String mptyp;//计量点种类

    private String erdat;//创建日期

    private String ernam;//创建者

    private String aedat;//更改日期

    private String aename;//更改人

    private String inact;//计量点没激活

    private String lvorm;//删除标识：逻辑删除；如果被删除了，则打上X标识

    private String atinn;//内部特性号(特征编号）:该字段需转换，未转换前是10位数字格式

    private Integer decim;//十进制位

    private Float mrmin;//范围下限:这个字段是科学计数，转换为10进制计数后需要除以100

    private Float mrmax;//范围上限:这个字段是科学计数，转换为10进制计数后需要除以100

    private Integer mrngu;//计量范围单位

    private String codct;//目录:常量：Z

    private String codgr;// 代码组

    private Integer checkseq;//点检顺序号

    private String checkreq;//点检要求

    private String checkcycle;//点检周期

    private String checkde;//点检部门

    private String joincheck;//是否参与点检：Y：表示参与点检；默认为Y，N：表示不参与点检

    private String checkkey;//是否关键点:Y：关键点，在点检时需拍照留证;N：不是关键点，点检时不需要拍照留证，单如果是点检不合格，则需要拍照留证；默认为N

    private String checkplan;//是否配置点检计划:N 否，表示默认每班点检，默认为N;Y 是，表示必须设置点检计划

    private String mronotice;//是否产生维修通知单:Y：表示在点检不合格时，产生维修通知单;N：表示不产生维修通知单，默认为N

    private String crdate;//配置创建日期

    private String crtime;//配置创建时间

    private String cruser;// 配置人

    private String chdate;//配置修改日期

    private String chtime;//配置修改时间

    private String chuser;//配置修改人

    public String getPoint() {
        return point;
    }

    public void setPoint(String point) {
        this.point = point;
    }

    public String getMpobj() {
        return mpobj;
    }

    public void setMpobj(String mpobj) {
        this.mpobj = mpobj;
    }

    public String getPttxt() {
        return pttxt;
    }

    public void setPttxt(String pttxt) {
        this.pttxt = pttxt;
    }

    public String getMptyp() {
        return mptyp;
    }

    public void setMptyp(String mptyp) {
        this.mptyp = mptyp;
    }

    public String getErdat() {
        return erdat;
    }

    public void setErdat(String erdat) {
        this.erdat = erdat;
    }

    public String getErnam() {
        return ernam;
    }

    public void setErnam(String ernam) {
        this.ernam = ernam;
    }

    public String getAedat() {
        return aedat;
    }

    public void setAedat(String aedat) {
        this.aedat = aedat;
    }

    public String getAename() {
        return aename;
    }

    public void setAename(String aename) {
        this.aename = aename;
    }

    public String getInact() {
        return inact;
    }

    public void setInact(String inact) {
        this.inact = inact;
    }

    public String getLvorm() {
        return lvorm;
    }

    public void setLvorm(String lvorm) {
        this.lvorm = lvorm;
    }

    public String getAtinn() {
        return atinn;
    }

    public void setAtinn(String atinn) {
        this.atinn = atinn;
    }

    public Integer getDecim() {
        return decim;
    }

    public void setDecim(Integer decim) {
        this.decim = decim;
    }

    public Float getMrmin() {
        return mrmin;
    }

    public void setMrmin(Float mrmin) {
        this.mrmin = mrmin;
    }

    public Float getMrmax() {
        return mrmax;
    }

    public void setMrmax(Float mrmax) {
        this.mrmax = mrmax;
    }

    public Integer getMrngu() {
        return mrngu;
    }

    public void setMrngu(Integer mrngu) {
        this.mrngu = mrngu;
    }

    public String getCodct() {
        return codct;
    }

    public void setCodct(String codct) {
        this.codct = codct;
    }

    public String getCodgr() {
        return codgr;
    }

    public void setCodgr(String codgr) {
        this.codgr = codgr;
    }

    public Integer getCheckseq() {
        return checkseq;
    }

    public void setCheckseq(Integer checkseq) {
        this.checkseq = checkseq;
    }

    public String getCheckreq() {
        return checkreq;
    }

    public void setCheckreq(String checkreq) {
        this.checkreq = checkreq;
    }

    public String getCheckcycle() {
        return checkcycle;
    }

    public void setCheckcycle(String checkcycle) {
        this.checkcycle = checkcycle;
    }

    public String getCheckde() {
        return checkde;
    }

    public void setCheckde(String checkde) {
        this.checkde = checkde;
    }

    public String getJoincheck() {
        return joincheck;
    }

    public void setJoincheck(String joincheck) {
        this.joincheck = joincheck;
    }

    public String getCheckkey() {
        return checkkey;
    }

    public void setCheckkey(String checkkey) {
        this.checkkey = checkkey;
    }

    public String getCheckplan() {
        return checkplan;
    }

    public void setCheckplan(String checkplan) {
        this.checkplan = checkplan;
    }

    public String getMronotice() {
        return mronotice;
    }

    public void setMronotice(String mronotice) {
        this.mronotice = mronotice;
    }

    public String getCrdate() {
        return crdate;
    }

    public void setCrdate(String crdate) {
        this.crdate = crdate;
    }

    public String getCrtime() {
        return crtime;
    }

    public void setCrtime(String crtime) {
        this.crtime = crtime;
    }

    public String getCruser() {
        return cruser;
    }

    public void setCruser(String cruser) {
        this.cruser = cruser;
    }

    public String getChdate() {
        return chdate;
    }

    public void setChdate(String chdate) {
        this.chdate = chdate;
    }

    public String getChtime() {
        return chtime;
    }

    public void setChtime(String chtime) {
        this.chtime = chtime;
    }

    public String getChuser() {
        return chuser;
    }

    public void setChuser(String chuser) {
        this.chuser = chuser;
    }
}
