package yj.core.pmequz.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable=true)
@Table(name = "sap_pm_equz")
public class Equz extends BaseDTO {
    @Id
    private String equnr;//设备编号

    private String eqktu;//设备描述
    @Id
    private String datbl;//有效截至日

    private String eqtyp;//设备种类

    private String typtx;//设备种类描述

    private String eqart;//对象类型：0802 模具，还有其他类型

    private String eartx;//对象类型描述

    private String tplnr;//功能位置

    private String pltxt;//功能位置描述

    private String arbpl;//工作中心

    private String ktext;//工作中心描述

    private String kostl;//成本中心

    private String ltext;//成本中心描述

    private String anlnr;//资产号

    private String txt50;//资产描述

    private String erdat;//创建日期

    private String ernam;//创建用户

    private String aedat;//更改日期

    private String aename;//更改用户

    private String timbl;//更改时间

    private String abbrnm;//模号简称

    private Integer moldnm;//模数

    private String matnr;//毛坯物料编号

    private String maktx;//物料描述

    private Integer dielifenm;//寿命压铸模次

    private Integer actualnm;//压铸模次

    private String inbdt;//开始日期（技术对象开始日期）

    private String typbz;//型号（制造商模型号）

    private String serge;//系列号（制造商系列号）

    private String herst;//制造商（资产制造商）

    private String baujj;// 制造年

    private String swerk;//维护工厂

    private String beber;//厂区

    private String abckz;//ABC标识（技术对象的ABC标识）

    private String iwerk;//计划工厂（维护计划工厂）

    private String ingrp;//计划人员组（客户服务和工厂维护的计划员组）

    private String rbnr;//类别参数文件

    private String bukrs;//公司代码

    private String atbez;//特征描述：ZPM03：出厂精度、ZPM04：现状精度、ZPM05：设备功率

    private String istat;//通知状态（通知的系统状态）：ISTAT（安装的）匹配 用户状态：编号10（在用），AVLB（可用）  匹配 用户状态：编号20（闲置），AVLB（可用）  匹配 用户状态：编号40（调出），ISTAT（安装的）标记（删除标记）匹配 用户状态：编号50（删除），ISTAT（安装的）匹配 用户状态：编号30（报废）

    private String estat;//用户状态：编号10（在用），编号20（闲置），编号30（报废），编号40（调出），编号50（删除）

    public String getEqunr() {
        return equnr;
    }

    public void setEqunr(String equnr) {
        this.equnr = equnr;
    }

    public String getEqktu() {
        return eqktu;
    }

    public void setEqktu(String eqktu) {
        this.eqktu = eqktu;
    }

    public String getDatbl() {
        return datbl;
    }

    public void setDatbl(String datbl) {
        this.datbl = datbl;
    }

    public String getEqtyp() {
        return eqtyp;
    }

    public void setEqtyp(String eqtyp) {
        this.eqtyp = eqtyp;
    }

    public String getTyptx() {
        return typtx;
    }

    public void setTyptx(String typtx) {
        this.typtx = typtx;
    }

    public String getEqart() {
        return eqart;
    }

    public void setEqart(String eqart) {
        this.eqart = eqart;
    }

    public String getEartx() {
        return eartx;
    }

    public void setEartx(String eartx) {
        this.eartx = eartx;
    }

    public String getTplnr() {
        return tplnr;
    }

    public void setTplnr(String tplnr) {
        this.tplnr = tplnr;
    }

    public String getPltxt() {
        return pltxt;
    }

    public void setPltxt(String pltxt) {
        this.pltxt = pltxt;
    }

    public String getArbpl() {
        return arbpl;
    }

    public void setArbpl(String arbpl) {
        this.arbpl = arbpl;
    }

    public String getKtext() {
        return ktext;
    }

    public void setKtext(String ktext) {
        this.ktext = ktext;
    }

    public String getKostl() {
        return kostl;
    }

    public void setKostl(String kostl) {
        this.kostl = kostl;
    }

    public String getLtext() {
        return ltext;
    }

    public void setLtext(String ltext) {
        this.ltext = ltext;
    }

    public String getAnlnr() {
        return anlnr;
    }

    public void setAnlnr(String anlnr) {
        this.anlnr = anlnr;
    }

    public String getTxt50() {
        return txt50;
    }

    public void setTxt50(String txt50) {
        this.txt50 = txt50;
    }

    public String getErdat() {
        return erdat;
    }

    public void setErdat(String erdat) {
        this.erdat = erdat;
    }

    public String getErnam() {
        return ernam;
    }

    public void setErnam(String ernam) {
        this.ernam = ernam;
    }

    public String getAedat() {
        return aedat;
    }

    public void setAedat(String aedat) {
        this.aedat = aedat;
    }

    public String getAename() {
        return aename;
    }

    public void setAename(String aename) {
        this.aename = aename;
    }

    public String getTimbl() {
        return timbl;
    }

    public void setTimbl(String timbl) {
        this.timbl = timbl;
    }

    public String getAbbrnm() {
        return abbrnm;
    }

    public void setAbbrnm(String abbrnm) {
        this.abbrnm = abbrnm;
    }

    public Integer getMoldnm() {
        return moldnm;
    }

    public void setMoldnm(Integer moldnm) {
        this.moldnm = moldnm;
    }

    public String getMatnr() {
        return matnr;
    }

    public void setMatnr(String matnr) {
        this.matnr = matnr;
    }

    public String getMaktx() {
        return maktx;
    }

    public void setMaktx(String maktx) {
        this.maktx = maktx;
    }

    public Integer getDielifenm() {
        return dielifenm;
    }

    public void setDielifenm(Integer dielifenm) {
        this.dielifenm = dielifenm;
    }

    public Integer getActualnm() {
        return actualnm;
    }

    public void setActualnm(Integer actualnm) {
        this.actualnm = actualnm;
    }

    public String getInbdt() {
        return inbdt;
    }

    public void setInbdt(String inbdt) {
        this.inbdt = inbdt;
    }

    public String getTypbz() {
        return typbz;
    }

    public void setTypbz(String typbz) {
        this.typbz = typbz;
    }

    public String getSerge() {
        return serge;
    }

    public void setSerge(String serge) {
        this.serge = serge;
    }

    public String getHerst() {
        return herst;
    }

    public void setHerst(String herst) {
        this.herst = herst;
    }

    public String getBaujj() {
        return baujj;
    }

    public void setBaujj(String baujj) {
        this.baujj = baujj;
    }

    public String getSwerk() {
        return swerk;
    }

    public void setSwerk(String swerk) {
        this.swerk = swerk;
    }

    public String getBeber() {
        return beber;
    }

    public void setBeber(String beber) {
        this.beber = beber;
    }

    public String getAbckz() {
        return abckz;
    }

    public void setAbckz(String abckz) {
        this.abckz = abckz;
    }

    public String getIwerk() {
        return iwerk;
    }

    public void setIwerk(String iwerk) {
        this.iwerk = iwerk;
    }

    public String getIngrp() {
        return ingrp;
    }

    public void setIngrp(String ingrp) {
        this.ingrp = ingrp;
    }

    public String getRbnr() {
        return rbnr;
    }

    public void setRbnr(String rbnr) {
        this.rbnr = rbnr;
    }

    public String getBukrs() {
        return bukrs;
    }

    public void setBukrs(String bukrs) {
        this.bukrs = bukrs;
    }

    public String getAtbez() {
        return atbez;
    }

    public void setAtbez(String atbez) {
        this.atbez = atbez;
    }

    public String getIstat() {
        return istat;
    }

    public void setIstat(String istat) {
        this.istat = istat;
    }

    public String getEstat() {
        return estat;
    }

    public void setEstat(String estat) {
        this.estat = estat;
    }
}
