package yj.core.wipproductscfg.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "wip_products_cfg")
public class ProductsCfg extends BaseDTO {
     @Id
     @GeneratedValue
      private String werks;

     @NotNull
      private Long lineId;

     @NotEmpty
      private String pmatnr;

     @NotEmpty
      private String matnr;
     @NotEmpty
      private  String lgort;
     @NotEmpty
      private String lgortassy;
     @NotEmpty
      private String lgortrew;
     @NotEmpty
      private int sxmax;
     @NotEmpty
      private int sxmin;

      private String kunnr;

      private String custmantr;

      private String custbarcodeynCarton;

      private String custbarcodeynBox;

      private Integer spostCarton;

      private Integer epostCarton;

      private Integer spostBox;

      private Integer epostBox;

      private Date creationDate; //创建时间

      private Long createdBy; //创建人

      private Date lastUpdatedDate; //更新时间

      private Long lastUpdatedBy; //更新人

    @Transient
    private String descriptions;
    @Transient
    private String maktx;

    private String matnr2;

    private String maktx2;

    private String kunnr1;
    @Transient
    private String name1;

    public String getDescriptions() {
        return descriptions;
    }

    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions;
    }

    public String getMaktx() {
        return maktx;
    }

    public void setMaktx(String maktx) {
        this.maktx = maktx;
    }

    public String getMatnr2() {
        return matnr2;
    }

    public void setMatnr2(String matnr2) {
        this.matnr2 = matnr2;
    }

    public String getMaktx2() {
        return maktx2;
    }

    public void setMaktx2(String maktx2) {
        this.maktx2 = maktx2;
    }

    public String getKunnr1() {
        return kunnr1;
    }

    public void setKunnr1(String kunnr1) {
        this.kunnr1 = kunnr1;
    }

    public String getName1() {
        return name1;
    }

    public void setName1(String name1) {
        this.name1 = name1;
    }

    public void setWerks(String werks){
         this.werks = werks;
     }

     public String getWerks(){
         return werks;
     }

     public void setLineId(Long lineId){
         this.lineId = lineId;
     }

     public Long getLineId(){
         return lineId;
     }

     public void setPmatnr(String pmatnr){
         this.pmatnr = pmatnr;
     }

     public String getPmatnr(){
         return pmatnr;
     }

     public void setMatnr(String matnr){
         this.matnr = matnr;
     }

     public String getMatnr(){
         return matnr;
     }

    public void setCreationDate(Date creationDate){
         this.creationDate = creationDate;
     }

     public Date getCreationDate(){
         return creationDate;
     }

     public void setCreatedBy(Long createdBy){
         this.createdBy = createdBy;
     }

     public Long getCreatedBy(){
         return createdBy;
     }

     public void setLastUpdatedDate(Date lastUpdatedDate){
         this.lastUpdatedDate = lastUpdatedDate;
     }

     public Date getLastUpdatedDate(){
         return lastUpdatedDate;
     }

     public void setLastUpdatedBy(Long lastUpdatedBy){
         this.lastUpdatedBy = lastUpdatedBy;
     }

     public Long getLastUpdatedBy(){
         return lastUpdatedBy;
     }

    public String getLgort() {
        return lgort;
    }

    public void setLgort(String lgort) {
        this.lgort = lgort;
    }

    public String getLgortassy() {
        return lgortassy;
    }

    public void setLgortassy(String lgortassy) {
        this.lgortassy = lgortassy;
    }

    public String getLgortrew() {
        return lgortrew;
    }

    public void setLgortrew(String lgortrew) {
        this.lgortrew = lgortrew;
    }

    public int getSxmax() {
        return sxmax;
    }

    public void setSxmax(int sxmax) {
        this.sxmax = sxmax;
    }

    public int getSxmin() {
        return sxmin;
    }

    public void setSxmin(int sxmin) {
        this.sxmin = sxmin;
    }

    public String getKunnr() {
        return kunnr;
    }

    public void setKunnr(String kunnr) {
        this.kunnr = kunnr;
    }

    public String getCustmantr() {
        return custmantr;
    }

    public void setCustmantr(String custmantr) {
        this.custmantr = custmantr;
    }

    public String getCustbarcodeynCarton() {
        return custbarcodeynCarton;
    }

    public void setCustbarcodeynCarton(String custbarcodeynCarton) {
        this.custbarcodeynCarton = custbarcodeynCarton;
    }

    public String getCustbarcodeynBox() {
        return custbarcodeynBox;
    }

    public void setCustbarcodeynBox(String custbarcodeynBox) {
        this.custbarcodeynBox = custbarcodeynBox;
    }

    public Integer getSpostCarton() {
        return spostCarton;
    }

    public void setSpostCarton(Integer spostCarton) {
        this.spostCarton = spostCarton;
    }

    public Integer getEpostCarton() {
        return epostCarton;
    }

    public void setEpostCarton(Integer epostCarton) {
        this.epostCarton = epostCarton;
    }

    public Integer getSpostBox() {
        return spostBox;
    }

    public void setSpostBox(Integer spostBox) {
        this.spostBox = spostBox;
    }

    public Integer getEpostBox() {
        return epostBox;
    }

    public void setEpostBox(Integer epostBox) {
        this.epostBox = epostBox;
    }
}
