package yj.core.pandian.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "sap_pandian")
public class Pandian extends BaseDTO {
     @NotEmpty
      private String werks;

     @NotEmpty
      private String aufnr;

     @NotEmpty
      private String zpgdbar;

     @Id
     @GeneratedValue
      private String zpgdbh;

      private String pddat;

      private String pddatbefore;

      private String pddatafter;

      private String pdtim;

      private String vornr;

      private String matnr;

      private String maktx;

      private String ltxa1;

      private Double gamng;

      private Double qrmng;

      private Date datum;

      private String zcfwz;

      private String zlylx;

      private String zmessage;

    @Transient
    private String created_by;

    @Transient
    private  String userName;//用户姓名

    @Transient
    private  Double cymng;

    @Transient
    private  String zpgdbarstr;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getZmessage() {
        return zmessage;
    }

    public void setZmessage(String zmessage) {
        this.zmessage = zmessage;
    }

    public void setWerks(String werks){
         this.werks = werks;
     }

     public String getWerks(){
         return werks;
     }

     public void setAufnr(String aufnr){
         this.aufnr = aufnr;
     }

     public String getAufnr(){
         return aufnr;
     }

     public void setZpgdbar(String zpgdbar){
         this.zpgdbar = zpgdbar;
     }

     public String getZpgdbar(){
         return zpgdbar;
     }

     public void setZpgdbh(String zpgdbh){
         this.zpgdbh = zpgdbh;
     }

     public String getZpgdbh(){
         return zpgdbh;
     }

     public void setPddat(String pddat){
         this.pddat = pddat;
     }

     public String getPddat(){
         return pddat;
     }

     public void setPdtim(String pdtim){
         this.pdtim = pdtim;
     }

     public String getPdtim(){
         return pdtim;
     }

     public void setVornr(String vornr){
         this.vornr = vornr;
     }

     public String getVornr(){
         return vornr;
     }

     public void setMatnr(String matnr){
         this.matnr = matnr;
     }

     public String getMatnr(){
         return matnr;
     }

     public void setMaktx(String maktx){
         this.maktx = maktx;
     }

     public String getMaktx(){
         return maktx;
     }

     public void setLtxa1(String ltxa1){
         this.ltxa1 = ltxa1;
     }

     public String getLtxa1(){
         return ltxa1;
     }

     public void setGamng(Double gamng){
         this.gamng = gamng;
     }

     public Double getGamng(){
         return gamng;
     }

     public void setQrmng(Double qrmng){
         this.qrmng = qrmng;
     }

     public Double getQrmng(){
         return qrmng;
     }

     public void setDatum(Date datum){
         this.datum = datum;
     }

     public Date getDatum(){
         return datum;
     }

     public void setZcfwz(String zcfwz){
         this.zcfwz = zcfwz;
     }

     public String getZcfwz(){
         return zcfwz;
     }

     public void setZlylx(String zlylx){
         this.zlylx = zlylx;
     }

     public String getZlylx(){
         return zlylx;
     }

    public String getCreated_by() {
        return created_by;
    }

    public void setCreated_by(String created_by) {
        this.created_by = created_by;
    }

    public String getPddatbefore() {
        return pddatbefore;
    }

    public void setPddatbefore(String pddatbefore) {
        this.pddatbefore = pddatbefore;
    }

    public String getPddatafter() {
        return pddatafter;
    }

    public void setPddatafter(String pddatafter) {
        this.pddatafter = pddatafter;
    }

    public Double getCymng() {
        return cymng;
    }

    public void setCymng(Double cynmg) {
        this.cymng = cynmg;
    }

    public String getZpgdbarstr() {
        return zpgdbarstr;
    }

    public void setZpgdbarstr(String zpgdbarstr) {
        this.zpgdbarstr = zpgdbarstr;
    }
}
