package yj.core.pandian.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "wip_pandiantmp")
public class Pandiantmp extends BaseDTO {
     @Id
     @GeneratedValue
      private String rcdid; //记录号

      private String werks; //工厂

      private String cardno; //流转卡号

      private String cardh; //工序行号

      private Double num; //数量

      private String operator; //盘点者员工编号

      private Date rcddat; //盘点日期

    @Transient
    private Long createdBy;

    @Transient
    private Date creationDate;

    @Transient
    private Long lastUpdatedBy;

    @Transient
    private  Date lastUpdateDate;


     public void setRcdid(String rcdid){
         this.rcdid = rcdid;
     }

     public String getRcdid(){
         return rcdid;
     }

     public void setWerks(String werks){
         this.werks = werks;
     }

     public String getWerks(){
         return werks;
     }

     public void setCardno(String cardno){
         this.cardno = cardno;
     }

     public String getCardno(){
         return cardno;
     }

     public void setCardh(String cardh){
         this.cardh = cardh;
     }

     public String getCardh(){
         return cardh;
     }

     public void setNum(Double num){
         this.num = num;
     }

     public Double getNum(){
         return num;
     }

     public void setOperator(String operator){
         this.operator = operator;
     }

     public String getOperator(){
         return operator;
     }

     public void setRcddat(Date rcddat){
         this.rcddat = rcddat;
     }

     public Date getRcddat(){
         return rcddat;
     }

    @Override
    public Long getCreatedBy() {
        return createdBy;
    }

    @Override
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    @Override
    public Date getCreationDate() {
        return creationDate;
    }

    @Override
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Override
    public Long getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    @Override
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Override
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    @Override
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}
