package yj.core.webservicepd.sender;

/**
 * Created by 917110140 on 2018/7/25.
 */
import yj.core.webservicepd.receiver.DTPANDIANRes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 *
 */
@WebService(name = "SI_PANDIAN_Sender_Syn", targetNamespace = "http://www.cq-yj.com/HAP/PANDIAN/Sender")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIPANDIANSenderSyn {

    /**
     *
     * @param mtPANDIANReq
     * @return returns com.cq_yj.hap.pandian.sender.DTPANDIANRes
     */
    @WebMethod(operationName = "SI_PANDIAN_Sender_Syn", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_PANDIAN_Res", targetNamespace = "http://www.cq-yj.com/HAP/PANDIAN/Sender", partName = "MT_PANDIAN_Res")
    public DTPANDIANRes siPANDIANSenderSyn(
            @WebParam(name = "MT_PANDIAN_Req", targetNamespace = "http://www.cq-yj.com/HAP/PANDIAN/Sender", partName = "MT_PANDIAN_Req") DTPANDIANReq mtPANDIANReq);

}
