package yj.core.webservice_newbg.sender;

/**
 * Created by 917110140 on 2018/8/11.
 */


import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 *
 * <pre>
 * SI_BAOGONG_Sender_SyncService service = new SI_BAOGONG_Sender_SyncService();
 * SIBAOGONGSenderSync portType = service.getHTTPPort();
 * portType.siBAOGONGSenderSync(...);
 * </pre>
 *
 * </p>
 *
 */
@WebServiceClient(name = "SI_BAOGONG_Sender_SyncService", targetNamespace = "http://www.cq-yj.com/HAP/BAOGONG/Sender", wsdlLocation = "resources/newbg.xml")
public class SIBAOGONGSenderSyncService extends Service {

    public final static URL WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(SIBAOGONGSenderSyncService.class.getName());

    static {
        URL url = null;
        url = SIBAOGONGSenderSyncService.class.getClassLoader().getResource("newbg.xml");
        System.out.println(url);
        WSDL_LOCATION = url;
    }

    public SIBAOGONGSenderSyncService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIBAOGONGSenderSyncService() {
        super(WSDL_LOCATION, new QName(
                "http://www.cq-yj.com/HAP/BAOGONG/Sender",
                "SI_BAOGONG_Sender_SyncService"));
    }

    /**
     *
     * @return returns SIBAOGONGSenderSync
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIBAOGONGSenderSync getHTTPPort() {
        return super.getPort(new QName(
                        "http://www.cq-yj.com/HAP/BAOGONG/Sender", "HTTP_Port"),
                SIBAOGONGSenderSync.class);
    }

    /**
     *
     * @return returns SIBAOGONGSenderSync
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIBAOGONGSenderSync getHTTPSPort() {
        return super.getPort(new QName(
                        "http://www.cq-yj.com/HAP/BAOGONG/Sender", "HTTPS_Port"),
                SIBAOGONGSenderSync.class);
    }

}


