package yj.core.webservice_newbg.sender;

/**
 * Created by 917110140 on 2018/8/11.
 */
import yj.core.webservice_newbg.receiver.DTBAOGONGSendRes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 *
 */
@WebService(name = "SI_BAOGONG_Sender_Sync", targetNamespace = "http://www.cq-yj.com/HAP/BAOGONG/Sender")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIBAOGONGSenderSync {

    /**
     *
     * @param mtBAOGONGSendReq
     * @return returns com.cq_yj.hap.baogong.sender.DTBAOGONGSendRes
     */
    @WebMethod(operationName = "SI_BAOGONG_Sender_Sync", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_BAOGONG_Send_Res", targetNamespace = "http://www.cq-yj.com/HAP/BAOGONG/Sender", partName = "MT_BAOGONG_Send_Res")
    public DTBAOGONGSendRes siBAOGONGSenderSync(
            @WebParam(name = "MT_BAOGONG_Send_Req", targetNamespace = "http://www.cq-yj.com/HAP/BAOGONG/Sender", partName = "MT_BAOGONG_Send_Req") DTBAOGONGSendReq mtBAOGONGSendReq);

}


