package yj.core.webservice_test.sender;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 *
 * <pre>
 * YJMethodImplService service = new YJMethodImplService();
 * YJMethodImpl portType = service.getYJMethodImplPort();
 * portType.queryOtherWeight(...);
 * </pre>
 *
 * </p>
 *
 */
@WebServiceClient(name = "YJMethodImplService", targetNamespace = "http://Impl.service.YJ.com/", wsdlLocation = "resources/test.xml")
public class YJMethodImplService extends Service {

    public final static URL WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(YJMethodImplService.class.getName());

    static {
        URL url = null;
        url = YJMethodImplService.class.getClassLoader().getResource("test.xml");
        System.out.println(url);
        WSDL_LOCATION = url;
    }

    public YJMethodImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public YJMethodImplService() {
        super(WSDL_LOCATION, new QName(
                "http://Impl.service.YJ.com/", "YJMethodImplService"));
    }

    /**
     *
     * @return returns YJMethodImpl
     */
    @WebEndpoint(name = "YJMethodImplPort")
    public YJMethodImpl getYJMethodImplPort() {
        return super.getPort(new QName("http://Impl.service.YJ.com/",
                "YJMethodImplPort"), YJMethodImpl.class);
    }

}

