package yj.core.webservice_test.sender;

import yj.core.webservice_test.dto.OReturnData;
import yj.core.webservice_test.dto.WReturnData;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 *
 */
@WebService(name = "YJMethodImpl", targetNamespace = "http://Impl.service.YJ.com/")
public interface YJMethodImpl {

    /**
     *
     * @param zsbeln
     * @return returns java.util.List<com.yj.service.impl.WReturnData>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryOtherWeight", targetNamespace = "http://Impl.service.YJ.com/", className = "com.yj.service.impl.QueryOtherWeight")
    @ResponseWrapper(localName = "queryOtherWeightResponse", targetNamespace = "http://Impl.service.YJ.com/", className = "com.yj.service.impl.QueryOtherWeightResponse")
    public List<WReturnData> queryOtherWeight(
            @WebParam(name = "ZSBELN", targetNamespace = "") String zsbeln);

    /**
     *
     * @param werks
     * @param senge
     * @param zlpn
     * @param bukrs
     * @param zsbeln
     * @param zfdat
     * @param ebeln
     * @param matnr
     * @param meins
     * @param ebelp
     * @param maktx
     * @param lifnr
     * @param pacnum
     * @return returns com.yj.service.impl.OReturnData
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertOrder", targetNamespace = "http://Impl.service.YJ.com/", className = "com.yj.service.impl.InsertOrder")
    @ResponseWrapper(localName = "insertOrderResponse", targetNamespace = "http://Impl.service.YJ.com/", className = "com.yj.service.impl.InsertOrderResponse")
    public OReturnData insertOrder(
            @WebParam(name = "BUKRS", targetNamespace = "") String bukrs,
            @WebParam(name = "WERKS", targetNamespace = "") String werks,
            @WebParam(name = "ZLPN", targetNamespace = "") String zlpn,
            @WebParam(name = "ZSBELN", targetNamespace = "") String zsbeln,
            @WebParam(name = "EBELN", targetNamespace = "") String ebeln,
            @WebParam(name = "EBELP", targetNamespace = "") String ebelp,
            @WebParam(name = "MATNR", targetNamespace = "") String matnr,
            @WebParam(name = "MAKTX", targetNamespace = "") String maktx,
            @WebParam(name = "ZFDAT", targetNamespace = "") String zfdat,
            @WebParam(name = "SENGE", targetNamespace = "") Double senge,
            @WebParam(name = "PACNUM", targetNamespace = "") int pacnum,
            @WebParam(name = "MEINS", targetNamespace = "") String meins,
            @WebParam(name = "LIFNR", targetNamespace = "") String lifnr);

}

