package yj.core.log.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "wip_logheader")
public class Logheader extends BaseDTO {
     @Id
     @GeneratedValue
      private String logid;

      private String attr1; //属性1

      private String attr2; //属性2

      private String attr3; //属性3

      private String attr4; //属性4

      private String attr5; //属性5

      private String attr6; //属性6

      private String attr7; //属性7

      private String attr8; //属性8

      private String attr9; //属性9

      private String attr10; //属性10

      private Long createdBy; //创建人

      private Date creationDate; //创建时间

      private Long lastUpdatedBy; //更新人

      private Date lastUpdatedDate;

    @Override
    public Long getCreatedBy() {
        return createdBy;
    }

    @Override
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    @Override
    public Date getCreationDate() {
        return creationDate;
    }

    @Override
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Override
    public Long getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    @Override
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    public Date getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    public void setLogid(String logid){
         this.logid = logid;
     }

     public String getLogid(){
         return logid;
     }

     public void setAttr1(String attr1){
         this.attr1 = attr1;
     }

     public String getAttr1(){
         return attr1;
     }

     public void setAttr2(String attr2){
         this.attr2 = attr2;
     }

     public String getAttr2(){
         return attr2;
     }

     public void setAttr3(String attr3){
         this.attr3 = attr3;
     }

     public String getAttr3(){
         return attr3;
     }

     public void setAttr4(String attr4){
         this.attr4 = attr4;
     }

     public String getAttr4(){
         return attr4;
     }

     public void setAttr5(String attr5){
         this.attr5 = attr5;
     }

     public String getAttr5(){
         return attr5;
     }

     public void setAttr6(String attr6){
         this.attr6 = attr6;
     }

     public String getAttr6(){
         return attr6;
     }

     public void setAttr7(String attr7){
         this.attr7 = attr7;
     }

     public String getAttr7(){
         return attr7;
     }

     public void setAttr8(String attr8){
         this.attr8 = attr8;
     }

     public String getAttr8(){
         return attr8;
     }

     public void setAttr9(String attr9){
         this.attr9 = attr9;
     }

     public String getAttr9(){
         return attr9;
     }

     public void setAttr10(String attr10){
         this.attr10 = attr10;
     }

     public String getAttr10(){
         return attr10;
     }

     }
