package yj.core.appidconf.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable=true)
@Table(name = "sap_appidconf")
public class Appidconf extends BaseDTO {
     @Id
     @GeneratedValue
      private String appid;

     @NotEmpty
      private String ktsch;

      private String appidTxt;

      private String ktschTxt;


     public void setAppid(String appid){
         this.appid = appid;
     }

     public String getAppid(){
         return appid;
     }

     public void setKtsch(String ktsch){
         this.ktsch = ktsch;
     }

     public String getKtsch(){
         return ktsch;
     }

     public void setAppidTxt(String appidTxt){
         this.appidTxt = appidTxt;
     }

     public String getAppidTxt(){
         return appidTxt;
     }

     public void setKtschTxt(String ktschTxt){
         this.ktschTxt = ktschTxt;
     }

     public String getKtschTxt(){
         return ktschTxt;
     }

     }
