package yj.core.zrwkhead.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable=true)
@Table(name = "wip_zrwkhead")
public class Zrwkhead extends BaseDTO {
     @Id
     @GeneratedValue
      private String zrwknum; //单据号

     @NotEmpty
      private String zotype; //取出原因

     @NotEmpty
      private String lineId; //生产线ID

     @NotEmpty
      private String arbpr; //工作中心

     @NotEmpty
      private String crdat;


     public void setZrwknum(String zrwknum){
         this.zrwknum = zrwknum;
     }

     public String getZrwknum(){
         return zrwknum;
     }

     public void setZotype(String zotype){
         this.zotype = zotype;
     }

     public String getZotype(){
         return zotype;
     }

     public void setLineId(String lineId){
         this.lineId = lineId;
     }

     public String getLineId(){
         return lineId;
     }

     public void setArbpr(String arbpr){
         this.arbpr = arbpr;
     }

     public String getArbpr(){
         return arbpr;
     }

     public void setCrdat(String crdat){
         this.crdat = crdat;
     }

     public String getCrdat(){
         return crdat;
     }

     }
