package yj.core.webservice_outsrgissue.sender;


import yj.core.webservice_outsrgissue.receiver.DTOUTSRGISSUERes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 *
 */
@WebService(name = "SI_OUTSRGISSUE_Sender_Sync", targetNamespace = "http://www.cq-yj.com/HAP/OUTSRGISSUE/Sender")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIOUTSRGISSUESenderSync {

    /**
     *
     * @param mtOUTSRGISSUEReq
     * @return returns com.cq_yj.hap.outsrgissue.sender.DTOUTSRGISSUERes
     */
    @WebMethod(operationName = "SI_OUTSRGISSUE_Sender_Sync", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_OUTSRGISSUE_Res", targetNamespace = "http://www.cq-yj.com/HAP/OUTSRGISSUE/Sender", partName = "MT_OUTSRGISSUE_Res")
    public DTOUTSRGISSUERes siOUTSRGISSUESenderSync(
            @WebParam(name = "MT_OUTSRGISSUE_Req", targetNamespace = "http://www.cq-yj.com/HAP/OUTSRGISSUE/Sender", partName = "MT_OUTSRGISSUE_Req") DTOUTSRGISSUEReq mtOUTSRGISSUEReq);

}
