package yj.core.wipdftrghlist.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "wip_dftrghlist")
public class Dftrghlist extends BaseDTO {
     @Id
     @GeneratedValue
      private String recordid; //不良毛坯处理单号

      private Long item; //行号

      private String werks; //工厂

     @NotEmpty
      private String matnr; //成品物料

     @NotEmpty
      private String lineId; //产线ID

     @NotEmpty
      private String zbanc; //机加班次

     @NotEmpty
      private String shift; //机加班组

      private Date gstrp; //机加生产日期

      private String zmpbar; //毛坯二维码

     @NotEmpty
      private String zpgdbar; //压铸工序流转卡号

     @NotEmpty
      private String zxhbar; //毛坯筐码

     @NotEmpty
      private String matnr2; //毛坯物料

     @NotEmpty
      private String ycharge; //毛坯生产批次

     @NotEmpty
      private String yshift; //压铸班组

     @NotEmpty
      private String yzbanc; //压铸班次

     @NotEmpty
      private String sfflg; //班标

     @NotEmpty
      private String diecd; //模号

      private String ygstrp; //压铸生产日期

     @NotEmpty
      private String code; //缺陷代码

     @NotEmpty
      private String tlevelcode; //二级缺陷代码

     @NotNull
      private Long menge; //原毛坯筐数量

     @NotNull
      private Long dfectQty; //待处理数量

     @NotEmpty
      private String gmein; //计量单位

      private String recordid1; //不合格品审理单1单号

      private String recordid2; //不合格品审理单2单号

      private String aufnr; //返工订单单号/采购单号

      private String cancelFlag; //撤销标识

      private Long cancelBy; //撤销人员

      private Date cancelDate; //撤销日期

      private String zpgdbarjj;//机加流转卡

      private String vornrjj;//机加首工序

    @Transient
     private String name1;

     private Long createdBy;

     private Date creationDate;

     private Long  lastUpdatedBy;

     private Date lastUpdateDate;

     private String deptId;

     private String depttxt;

     private String plineId;

     private String deslinetxt;

     private String desmianlinetxt;

     private String maktx;

     private String maktx2;

     private String kurztext;

     private String ztext;

     private String zbanz;

     private String kunnr;

     private String sortl;

     private String charg;

     private String zqxdm;

     private String zissuetxt;

     private String zpgdbar2;

     private String departbm;

     private String departcj;

     private String vornr1;

     private String userName;

     private String userNameQC;

    public String getZpgdbar2() {
        return zpgdbar2;
    }

    public void setZpgdbar2(String zpgdbar2) {
        this.zpgdbar2 = zpgdbar2;
    }

    public String getCharg() {
        return charg;
    }

    public void setCharg(String charg) {
        this.charg = charg;
    }

    public String getZqxdm() {
        return zqxdm;
    }

    public void setZqxdm(String zqxdm) {
        this.zqxdm = zqxdm;
    }

    public String getZissuetxt() {
        return zissuetxt;
    }

    public void setZissuetxt(String zissuetxt) {
        this.zissuetxt = zissuetxt;
    }

    @Override
    public Long getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    @Override
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Override
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    @Override
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    @Override
    public Long getCreatedBy() {
        return createdBy;
    }

    @Override
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    @Override
    public Date getCreationDate() {
        return creationDate;
    }

    @Override
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public void setRecordid(String recordid){
         this.recordid = recordid;
     }

     public String getRecordid(){
         return recordid;
     }

     public void setItem(Long item){
         this.item = item;
     }

     public Long getItem(){
         return item;
     }

     public void setWerks(String werks){
         this.werks = werks;
     }

     public String getWerks(){
         return werks;
     }

     public void setMatnr(String matnr){
         this.matnr = matnr;
     }

     public String getMatnr(){
         return matnr;
     }

     public void setLineId(String lineId){
         this.lineId = lineId;
     }

     public String getLineId(){
         return lineId;
     }

     public void setZbanc(String zbanc){
         this.zbanc = zbanc;
     }

     public String getZbanc(){
         return zbanc;
     }

     public void setShift(String shift){
         this.shift = shift;
     }

     public String getShift(){
         return shift;
     }

     public void setGstrp(Date gstrp){
         this.gstrp = gstrp;
     }

     public Date getGstrp(){
         return gstrp;
     }

     public void setZmpbar(String zmpbar){
         this.zmpbar = zmpbar;
     }

     public String getZmpbar(){
         return zmpbar;
     }

     public void setZpgdbar(String zpgdbar){
         this.zpgdbar = zpgdbar;
     }

     public String getZpgdbar(){
         return zpgdbar;
     }

     public void setZxhbar(String zxhbar){
         this.zxhbar = zxhbar;
     }

     public String getZxhbar(){
         return zxhbar;
     }

     public void setMatnr2(String matnr2){
         this.matnr2 = matnr2;
     }

     public String getMatnr2(){
         return matnr2;
     }

     public void setYcharge(String ycharge){
         this.ycharge = ycharge;
     }

     public String getYcharge(){
         return ycharge;
     }

     public void setYshift(String yshift){
         this.yshift = yshift;
     }

     public String getYshift(){
         return yshift;
     }

     public void setYzbanc(String yzbanc){
         this.yzbanc = yzbanc;
     }

     public String getYzbanc(){
         return yzbanc;
     }

     public void setSfflg(String sfflg){
         this.sfflg = sfflg;
     }

     public String getSfflg(){
         return sfflg;
     }

     public void setDiecd(String diecd){
         this.diecd = diecd;
     }

     public String getDiecd(){
         return diecd;
     }

     public void setYgstrp(String ygstrp){
         this.ygstrp = ygstrp;
     }

     public String getYgstrp(){
         return ygstrp;
     }

     public void setCode(String code){
         this.code = code;
     }

     public String getCode(){
         return code;
     }

     public void setTlevelcode(String tlevelcode){
         this.tlevelcode = tlevelcode;
     }

     public String getTlevelcode(){
         return tlevelcode;
     }

     public void setMenge(Long menge){
         this.menge = menge;
     }

     public Long getMenge(){
         return menge;
     }

     public void setDfectQty(Long dfectQty){
         this.dfectQty = dfectQty;
     }

     public Long getDfectQty(){
         return dfectQty;
     }

     public void setGmein(String gmein){
         this.gmein = gmein;
     }

     public String getGmein(){
         return gmein;
     }

     public void setRecordid1(String recordid1){
         this.recordid1 = recordid1;
     }

     public String getRecordid1(){
         return recordid1;
     }

     public void setRecordid2(String recordid2){
         this.recordid2 = recordid2;
     }

     public String getRecordid2(){
         return recordid2;
     }

     public void setAufnr(String aufnr){
         this.aufnr = aufnr;
     }

     public String getAufnr(){
         return aufnr;
     }

     public void setCancelFlag(String cancelFlag){
         this.cancelFlag = cancelFlag;
     }

     public String getCancelFlag(){
         return cancelFlag;
     }

     public void setCancelBy(Long cancelBy){
         this.cancelBy = cancelBy;
     }

     public Long getCancelBy(){
         return cancelBy;
     }

     public void setCancelDate(Date cancelDate){
         this.cancelDate = cancelDate;
     }

     public Date getCancelDate(){
         return cancelDate;
     }


    public String getDeptId() {
        return deptId;
    }

    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }

    public String getDepttxt() {
        return depttxt;
    }

    public void setDepttxt(String depttxt) {
        this.depttxt = depttxt;
    }

    public String getPlineId() {
        return plineId;
    }

    public void setPlineId(String plineId) {
        this.plineId = plineId;
    }

    public String getDeslinetxt() {
        return deslinetxt;
    }

    public void setDeslinetxt(String deslinetxt) {
        this.deslinetxt = deslinetxt;
    }

    public String getDesmianlinetxt() {
        return desmianlinetxt;
    }

    public void setDesmianlinetxt(String desmianlinetxt) {
        this.desmianlinetxt = desmianlinetxt;
    }

    public String getMaktx2() {
        return maktx2;
    }

    public void setMaktx2(String maktx2) {
        this.maktx2 = maktx2;
    }

    public String getKurztext() {
        return kurztext;
    }

    public void setKurztext(String kurztext) {
        this.kurztext = kurztext;
    }

    public String getZtext() {
        return ztext;
    }

    public void setZtext(String ztext) {
        this.ztext = ztext;
    }

    public String getZbanz() {
        return zbanz;
    }

    public void setZbanz(String zbanz) {
        this.zbanz = zbanz;
    }

    public String getKunnr() {
        return kunnr;
    }

    public void setKunnr(String kunnr) {
        this.kunnr = kunnr;
    }

    public String getSortl() {
        return sortl;
    }

    public void setSortl(String sortl) {
        this.sortl = sortl;
    }

    public String getMaktx() {
        return maktx;
    }

    public void setMaktx(String maktx) {
        this.maktx = maktx;
    }

    public String getDepartbm() {
        return departbm;
    }

    public void setDepartbm(String departbm) {
        this.departbm = departbm;
    }

    public String getDepartcj() {
        return departcj;
    }

    public void setDepartcj(String departcj) {
        this.departcj = departcj;
    }

    public String getVornr1() {
        return vornr1;
    }

    public void setVornr1(String vornr1) {
        this.vornr1 = vornr1;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserNameQC() {
        return userNameQC;
    }

    public void setUserNameQC(String userNameQC) {
        this.userNameQC = userNameQC;
    }

    public String getZpgdbarjj() {
        return zpgdbarjj;
    }

    public void setZpgdbarjj(String zpgdbarjj) {
        this.zpgdbarjj = zpgdbarjj;
    }

    public String getVornrjj() {
        return vornrjj;
    }

    public void setVornrjj(String vornrjj) {
        this.vornrjj = vornrjj;
    }

    public String getName1() {
        return name1;
    }

    public void setName1(String name1) {
        this.name1 = name1;
    }
}
