package yj.core.webservice_migo.sender;

import yj.core.webservice_migo.receiver.DTMIGOSendRes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 *
 */
@WebService(name = "SI_MIGO_Sender_Sync", targetNamespace = "http://www.cq-yj.com/HAP/MIGO/Sender")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIMIGOSenderSync {

    /**
     *
     * @param mtMIGOSendReq
     * @return returns com.cq_yj.hap.migo.sender.DTMIGOSendRes
     */
    @WebMethod(operationName = "SI_MIGO_Sender_Sync", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_MIGO_Send_Res", targetNamespace = "http://www.cq-yj.com/HAP/MIGO/Sender", partName = "MT_MIGO_Send_Res")
    public DTMIGOSendRes siMIGOSenderSync(
            @WebParam(name = "MT_MIGO_Send_Req", targetNamespace = "http://www.cq-yj.com/HAP/MIGO/Sender", partName = "MT_MIGO_Send_Req") DTMIGOSendReq mtMIGOSendReq);

}

