package yj.core.batchpds.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable=true)
@Table(name = "sap_batchpdlogs")
public class Batchpdlogs extends BaseDTO {
     @Id
     @GeneratedValue
      private String zpgdbar; //冲销流转卡

      private String vornr; //工序

      private String matnr; //物料编码

      private String aufnr; //生产订单

      private String wirteoffdate; //冲销日期

      private String wirteoffflag; //冲销结果标识

      private String wirteoffmsg;

      private String postdate; //报工日期

      private String postflag; //报工结果标识

      private String postmsg;


     public void setZpgdbar(String zpgdbar){
         this.zpgdbar = zpgdbar;
     }

     public String getZpgdbar(){
         return zpgdbar;
     }

     public void setVornr(String vornr){
         this.vornr = vornr;
     }

     public String getVornr(){
         return vornr;
     }

     public void setMatnr(String matnr){
         this.matnr = matnr;
     }

     public String getMatnr(){
         return matnr;
     }

     public void setAufnr(String aufnr){
         this.aufnr = aufnr;
     }

     public String getAufnr(){
         return aufnr;
     }

     public void setWirteoffdate(String wirteoffdate){
         this.wirteoffdate = wirteoffdate;
     }

     public String getWirteoffdate(){
         return wirteoffdate;
     }

     public void setWirteoffflag(String wirteoffflag){
         this.wirteoffflag = wirteoffflag;
     }

     public String getWirteoffflag(){
         return wirteoffflag;
     }

     public void setWirteoffmsg(String wirteoffmsg){
         this.wirteoffmsg = wirteoffmsg;
     }

     public String getWirteoffmsg(){
         return wirteoffmsg;
     }

     public void setPostdate(String postdate){
         this.postdate = postdate;
     }

     public String getPostdate(){
         return postdate;
     }

     public void setPostflag(String postflag){
         this.postflag = postflag;
     }

     public String getPostflag(){
         return postflag;
     }

     public void setPostmsg(String postmsg){
         this.postmsg = postmsg;
     }

     public String getPostmsg(){
         return postmsg;
     }

     }
