package yj.core.imfpmcheckdoc.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable=true)
@Table(name = "imf_pm_checkdoc")
public class Checkdoc extends BaseDTO {
    @Id
    @GeneratedValue
    private Long checkdoc;//编号

    private String mpobj;//设备编号

    private String eqktu;//设备描述

    private String point;//计量点

    private String pttxt;//计量点描述

    private String checkreq;//点检要求

    private String checkcycle;//点检周期

    private String checkde;//点检部门

    private String iwerk;//工厂

    private String tplnr;//功能位置

    private String pltxt;//功能位置描述

    private String arbpl;//工作中心

    private String ktext;//工作中心描述

    private String checkdate;//点检日期

    private String checktime;//点检时间

    private String checkshift;//点检班次

    private String checkuser;//点检人

    private String checkobject;//点检类型:C：点检；R：复检

    private Integer checkplanId;//点检计划编号

    private String codct;//目录:常量：Z

    private String codgr;// 代码组

    private String kurztext1;//代码组文本

    private String code;//代码

    private String kurztext2;//代码文本

    private String atinn;//内部特性号(特征编号）:该字段需转换，未转换前是10位数字格式

    private String atbez;//特性描述

    private Float readg;//计量读数

    private Float mrmin;//范围下限:这个字段是科学计数，转换为10进制计数后需要除以100

    private Float mrmax;//范围上限:这个字段是科学计数，转换为10进制计数后需要除以100

    private Integer mrngu;//计量范围单位

    private String mdtxt;//处理说明

    private String checkSubdate;//点检提交日期

    private String checkSubtime;//点检提交时间

    private String costate;// 确认标志：N：未确认；默认为未确认；Y：已确认

    private String codate;//确认日期

    private String cotime;//确认时间

    private String couser;//确认人员

    private String mronoticrFlag;//产生维修通知单标记：1=未产生维修通知单；2=已产生维修通知单   默认为1

    private String qmnum;//维修通知单

    public Long getCheckdoc() {
        return checkdoc;
    }

    public void setCheckdoc(Long checkdoc) {
        this.checkdoc = checkdoc;
    }

    public String getMpobj() {
        return mpobj;
    }

    public void setMpobj(String mpobj) {
        this.mpobj = mpobj;
    }

    public String getEqktu() {
        return eqktu;
    }

    public void setEqktu(String eqktu) {
        this.eqktu = eqktu;
    }

    public String getPoint() {
        return point;
    }

    public void setPoint(String point) {
        this.point = point;
    }

    public String getPttxt() {
        return pttxt;
    }

    public void setPttxt(String pttxt) {
        this.pttxt = pttxt;
    }

    public String getCheckreq() {
        return checkreq;
    }

    public void setCheckreq(String checkreq) {
        this.checkreq = checkreq;
    }

    public String getCheckcycle() {
        return checkcycle;
    }

    public void setCheckcycle(String checkcycle) {
        this.checkcycle = checkcycle;
    }

    public String getCheckde() {
        return checkde;
    }

    public void setCheckde(String checkde) {
        this.checkde = checkde;
    }

    public String getIwerk() {
        return iwerk;
    }

    public void setIwerk(String iwerk) {
        this.iwerk = iwerk;
    }

    public String getTplnr() {
        return tplnr;
    }

    public void setTplnr(String tplnr) {
        this.tplnr = tplnr;
    }

    public String getPltxt() {
        return pltxt;
    }

    public void setPltxt(String pltxt) {
        this.pltxt = pltxt;
    }

    public String getArbpl() {
        return arbpl;
    }

    public void setArbpl(String arbpl) {
        this.arbpl = arbpl;
    }

    public String getKtext() {
        return ktext;
    }

    public void setKtext(String ktext) {
        this.ktext = ktext;
    }

    public String getCheckdate() {
        return checkdate;
    }

    public void setCheckdate(String checkdate) {
        this.checkdate = checkdate;
    }

    public String getChecktime() {
        return checktime;
    }

    public void setChecktime(String checktime) {
        this.checktime = checktime;
    }

    public String getCheckshift() {
        return checkshift;
    }

    public void setCheckshift(String checkshift) {
        this.checkshift = checkshift;
    }

    public String getCheckuser() {
        return checkuser;
    }

    public void setCheckuser(String checkuser) {
        this.checkuser = checkuser;
    }

    public String getCheckobject() {
        return checkobject;
    }

    public void setCheckobject(String checkobject) {
        this.checkobject = checkobject;
    }

    public Integer getCheckplanId() {
        return checkplanId;
    }

    public void setCheckplanId(Integer checkplanId) {
        this.checkplanId = checkplanId;
    }

    public String getCodct() {
        return codct;
    }

    public void setCodct(String codct) {
        this.codct = codct;
    }

    public String getCodgr() {
        return codgr;
    }

    public void setCodgr(String codgr) {
        this.codgr = codgr;
    }

    public String getKurztext1() {
        return kurztext1;
    }

    public void setKurztext1(String kurztext1) {
        this.kurztext1 = kurztext1;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getKurztext2() {
        return kurztext2;
    }

    public void setKurztext2(String kurztext2) {
        this.kurztext2 = kurztext2;
    }

    public String getAtinn() {
        return atinn;
    }

    public void setAtinn(String atinn) {
        this.atinn = atinn;
    }

    public String getAtbez() {
        return atbez;
    }

    public void setAtbez(String atbez) {
        this.atbez = atbez;
    }

    public Float getReadg() {
        return readg;
    }

    public void setReadg(Float readg) {
        this.readg = readg;
    }

    public Float getMrmin() {
        return mrmin;
    }

    public void setMrmin(Float mrmin) {
        this.mrmin = mrmin;
    }

    public Float getMrmax() {
        return mrmax;
    }

    public void setMrmax(Float mrmax) {
        this.mrmax = mrmax;
    }

    public Integer getMrngu() {
        return mrngu;
    }

    public void setMrngu(Integer mrngu) {
        this.mrngu = mrngu;
    }

    public String getMdtxt() {
        return mdtxt;
    }

    public void setMdtxt(String mdtxt) {
        this.mdtxt = mdtxt;
    }

    public String getCheckSubdate() {
        return checkSubdate;
    }

    public void setCheckSubdate(String checkSubdate) {
        this.checkSubdate = checkSubdate;
    }

    public String getCheckSubtime() {
        return checkSubtime;
    }

    public void setCheckSubtime(String checkSubtime) {
        this.checkSubtime = checkSubtime;
    }

    public String getCostate() {
        return costate;
    }

    public void setCostate(String costate) {
        this.costate = costate;
    }

    public String getCodate() {
        return codate;
    }

    public void setCodate(String codate) {
        this.codate = codate;
    }

    public String getCotime() {
        return cotime;
    }

    public void setCotime(String cotime) {
        this.cotime = cotime;
    }

    public String getCouser() {
        return couser;
    }

    public void setCouser(String couser) {
        this.couser = couser;
    }

    public String getMronoticrFlag() {
        return mronoticrFlag;
    }

    public void setMronoticrFlag(String mronoticrFlag) {
        this.mronoticrFlag = mronoticrFlag;
    }

    public String getQmnum() {
        return qmnum;
    }

    public void setQmnum(String qmnum) {
        this.qmnum = qmnum;
    }
}
