package yj.core.pmqpgr.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable=true)
@Table(name = "imf_pm_checkdoc")
public class Qpgr extends BaseDTO {
    @Id
    private String codct;//目录:常量：Z

    private String codgr;// 代码组

    private String kurztext1;//代码组文本

    private String ersteller;//创建人

    private String eDatum;//创建日期

    private String aenderer;//修改人

    private String aDatum;//修改日期

    private String inaktiv;//代码组状态

    private String code;//代码

    private String kurztext2;//代码文本

    private String zcodeObject;//代码类型：C：点检；R：复检；默认为空

    private String zrepeatCheck;//触发复检：Y：是；N：否；默认为空

    private String crdate;//配置创建日期

    private String crtime;//配置创建时间

    private String cruser;// 配置人

    private String chdate;//配置修改日期

    private String chtime;//配置修改时间

    private String chuser;//配置修改人

    public String getCodct() {
        return codct;
    }

    public void setCodct(String codct) {
        this.codct = codct;
    }

    public String getCodgr() {
        return codgr;
    }

    public void setCodgr(String codgr) {
        this.codgr = codgr;
    }

    public String getKurztext1() {
        return kurztext1;
    }

    public void setKurztext1(String kurztext1) {
        this.kurztext1 = kurztext1;
    }

    public String getErsteller() {
        return ersteller;
    }

    public void setErsteller(String ersteller) {
        this.ersteller = ersteller;
    }

    public String geteDatum() {
        return eDatum;
    }

    public void seteDatum(String eDatum) {
        this.eDatum = eDatum;
    }

    public String getAenderer() {
        return aenderer;
    }

    public void setAenderer(String aenderer) {
        this.aenderer = aenderer;
    }

    public String getaDatum() {
        return aDatum;
    }

    public void setaDatum(String aDatum) {
        this.aDatum = aDatum;
    }

    public String getInaktiv() {
        return inaktiv;
    }

    public void setInaktiv(String inaktiv) {
        this.inaktiv = inaktiv;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getKurztext2() {
        return kurztext2;
    }

    public void setKurztext2(String kurztext2) {
        this.kurztext2 = kurztext2;
    }

    public String getZcodeObject() {
        return zcodeObject;
    }

    public void setZcodeObject(String zcodeObject) {
        this.zcodeObject = zcodeObject;
    }

    public String getZrepeatCheck() {
        return zrepeatCheck;
    }

    public void setZrepeatCheck(String zrepeatCheck) {
        this.zrepeatCheck = zrepeatCheck;
    }

    public String getCrdate() {
        return crdate;
    }

    public void setCrdate(String crdate) {
        this.crdate = crdate;
    }

    public String getCrtime() {
        return crtime;
    }

    public void setCrtime(String crtime) {
        this.crtime = crtime;
    }

    public String getCruser() {
        return cruser;
    }

    public void setCruser(String cruser) {
        this.cruser = cruser;
    }

    public String getChdate() {
        return chdate;
    }

    public void setChdate(String chdate) {
        this.chdate = chdate;
    }

    public String getChtime() {
        return chtime;
    }

    public void setChtime(String chtime) {
        this.chtime = chtime;
    }

    public String getChuser() {
        return chuser;
    }

    public void setChuser(String chuser) {
        this.chuser = chuser;
    }
}
