package yj.core.ztbc0018.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "sap_ztbc0018")
public class Ztbc0018 extends BaseDTO {
     @Id
     @GeneratedValue
      private String id; //唯一ID

     @NotEmpty
      private String lineId; //生产线ID

     @NotEmpty
      private String zxhbar; //压铸工序毛坯筐码

     @NotEmpty
      private String zpgdbar2; //压铸工序流转卡号

      private String mblnr; //物料凭证号SAP返回

      private String mjahr; //物料凭证年度SAP返回

      private Long bmenge; //箱号数量

      private Long smenge; //箱号上线数量

      private String meins; //单位

      private String lgort; //库存地点

      private String zspty; //审批状态  OA返回

      private String zspbz; //审批标识  是否需要审批：Y/N

      private String zdlty; //处理状态 0：未处理 1：已处理

      private Date creationDate; //创建时间

     @NotNull
      private Long createdBy; //创建人

      private Date lastUpdatedDate; //更新时间

      private Long lastUpdatedBy; //更新人


     public void setId(String id){
         this.id = id;
     }

     public String getId(){
         return id;
     }

     public void setLineId(String lineId){
         this.lineId = lineId;
     }

     public String getLineId(){
         return lineId;
     }

     public void setZxhbar(String zxhbar){
         this.zxhbar = zxhbar;
     }

     public String getZxhbar(){
         return zxhbar;
     }

     public void setZpgdbar2(String zpgdbar2){
         this.zpgdbar2 = zpgdbar2;
     }

     public String getZpgdbar2(){
         return zpgdbar2;
     }

     public void setMblnr(String mblnr){
         this.mblnr = mblnr;
     }

     public String getMblnr(){
         return mblnr;
     }

     public void setMjahr(String mjahr){
         this.mjahr = mjahr;
     }

     public String getMjahr(){
         return mjahr;
     }

    public Long getBmenge() {
        return bmenge;
    }

    public void setBmenge(Long bmenge) {
        this.bmenge = bmenge;
    }

    public Long getSmenge() {
        return smenge;
    }

    public void setSmenge(Long smenge) {
        this.smenge = smenge;
    }

    public void setMeins(String meins){
         this.meins = meins;
     }

     public String getMeins(){
         return meins;
     }

     public void setLgort(String lgort){
         this.lgort = lgort;
     }

     public String getLgort(){
         return lgort;
     }

     public void setZspty(String zspty){
         this.zspty = zspty;
     }

     public String getZspty(){
         return zspty;
     }

     public void setZspbz(String zspbz){
         this.zspbz = zspbz;
     }

     public String getZspbz(){
         return zspbz;
     }

     public void setZdlty(String zdlty){
         this.zdlty = zdlty;
     }

     public String getZdlty(){
         return zdlty;
     }

     public void setCreationDate(Date creationDate){
         this.creationDate = creationDate;
     }

     public Date getCreationDate(){
         return creationDate;
     }

     public void setCreatedBy(Long createdBy){
         this.createdBy = createdBy;
     }

     public Long getCreatedBy(){
         return createdBy;
     }

     public void setLastUpdatedDate(Date lastUpdatedDate){
         this.lastUpdatedDate = lastUpdatedDate;
     }

     public Date getLastUpdatedDate(){
         return lastUpdatedDate;
     }

     public void setLastUpdatedBy(Long lastUpdatedBy){
         this.lastUpdatedBy = lastUpdatedBy;
     }

     public Long getLastUpdatedBy(){
         return lastUpdatedBy;
     }

     }
