package yj.core.wiparea.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "wip_area")
public class Area extends BaseDTO {
     @Id
     @GeneratedValue
      private String werks;

     @NotEmpty
      private String areano; //暂存区代号

     @NotEmpty
      private String areatxt;

      private String location; //暂存区地点

      private String stwks; //工作中心

      private String manager; //责任人

      private String capacity; //容量

      private String capunit; //容量单位

      private Double quota; //定额库存量

      private String qtaunit;

      private Double avgtrastm;

      private String tmunit;

      private Long cycletm;

      private String isconfirm; //转入是否确认

      private String remark; //备注

    private Date creationDate; //创建时间

    @Transient
    private String userName;

    @NotNull
    private Long createdBy; //创建人

    private Date lastUpdateDate; //更新时间

    private Long lastUpdatedBy; //更新人


     public void setWerks(String werks){
         this.werks = werks;
     }

     public String getWerks(){
         return werks;
     }

     public void setAreano(String areano){
         this.areano = areano;
     }

     public String getAreano(){
         return areano;
     }

     public void setAreatxt(String areatxt){
         this.areatxt = areatxt;
     }

     public String getAreatxt(){
         return areatxt;
     }

     public void setLocation(String location){
         this.location = location;
     }

     public String getLocation(){
         return location;
     }

     public void setStwks(String stwks){
         this.stwks = stwks;
     }

     public String getStwks(){
         return stwks;
     }

     public void setManager(String manager){
         this.manager = manager;
     }

     public String getManager(){
         return manager;
     }

     public void setCapacity(String capacity){
         this.capacity = capacity;
     }

     public String getCapacity(){
         return capacity;
     }

     public void setCapunit(String capunit){
         this.capunit = capunit;
     }

     public String getCapunit(){
         return capunit;
     }

     public void setQuota(Double quota){
         this.quota = quota;
     }

     public Double getQuota(){
         return quota;
     }

     public void setQtaunit(String qtaunit){
         this.qtaunit = qtaunit;
     }

     public String getQtaunit(){
         return qtaunit;
     }

     public void setAvgtrastm(Double avgtrastm){
         this.avgtrastm = avgtrastm;
     }

     public Double getAvgtrastm(){
         return avgtrastm;
     }

     public void setTmunit(String tmunit){
         this.tmunit = tmunit;
     }

     public String getTmunit(){
         return tmunit;
     }

     public void setCycletm(Long cycletm){
         this.cycletm = cycletm;
     }

     public Long getCycletm(){
         return cycletm;
     }

     public void setIsconfirm(String isconfirm){
         this.isconfirm = isconfirm;
     }

     public String getIsconfirm(){
         return isconfirm;
     }

     public void setRemark(String remark){
         this.remark = remark;
     }

     public String getRemark(){
         return remark;
     }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Override
    public Date getCreationDate() {
        return creationDate;
    }

    @Override
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Override
    public Long getCreatedBy() {
        return createdBy;
    }

    @Override
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    @Override
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    @Override
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    @Override
    public Long getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    @Override
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

}
