package yj.kanb.marcres.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable=true)
@Table(name = "vb_marc_res")
public class MarcRes extends BaseDTO {
     @Id
     @GeneratedValue
      private String werks; //工厂

     @NotEmpty
      private String matnr; //物料编码

      private Long fileidA; //A面图片ID

      private Long fileidB; //B面图片ID

    private String bukrs;//公司

      private String attr1;

      private String attr2;

      private String attr3;

      private String attr4;

      private String attr5;

      private String attr6;

      private String attr7;

    public String getBukrs() {
        return bukrs;
    }

    public void setBukrs(String bukrs) {
        this.bukrs = bukrs;
    }

    public void setWerks(String werks){
         this.werks = werks;
     }

     public String getWerks(){
         return werks;
     }

     public void setMatnr(String matnr){
         this.matnr = matnr;
     }

     public String getMatnr(){
         return matnr;
     }

     public void setFileidA(Long fileidA){
         this.fileidA = fileidA;
     }

     public Long getFileidA(){
         return fileidA;
     }

     public void setFileidB(Long fileidB){
         this.fileidB = fileidB;
     }

     public Long getFileidB(){
         return fileidB;
     }

     public void setAttr1(String attr1){
         this.attr1 = attr1;
     }

     public String getAttr1(){
         return attr1;
     }

     public void setAttr2(String attr2){
         this.attr2 = attr2;
     }

     public String getAttr2(){
         return attr2;
     }

     public void setAttr3(String attr3){
         this.attr3 = attr3;
     }

     public String getAttr3(){
         return attr3;
     }

     public void setAttr4(String attr4){
         this.attr4 = attr4;
     }

     public String getAttr4(){
         return attr4;
     }

     public void setAttr5(String attr5){
         this.attr5 = attr5;
     }

     public String getAttr5(){
         return attr5;
     }

     public void setAttr6(String attr6){
         this.attr6 = attr6;
     }

     public String getAttr6(){
         return attr6;
     }

     public void setAttr7(String attr7){
         this.attr7 = attr7;
     }

     public String getAttr7(){
         return attr7;
     }

     }
