package yj.core.resb.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "sap_resb")
public class Resb extends BaseDTO {
     @NotEmpty
      private String rsnum;

     @Id
     @GeneratedValue
      private String rspos;

      private String postp;

      private String posnr;

      private String xloek;

      private String matnr;

      private String maktx;

      private String werks;

      private String lgort;

      private Double bdmng;

      private String meins;

      private String rgekz;

      private String aufpl;

      private String vornr;

      private String aplzl;

      @Transient
      private Date creationDate; //创建时间
    @Transient
      private Date lastUpdatedDate; //更新时间

     public void setRsnum(String rsnum){
         this.rsnum = rsnum;
     }

     public String getRsnum(){
         return rsnum;
     }

     public void setRspos(String rspos){
         this.rspos = rspos;
     }

     public String getRspos(){
         return rspos;
     }

     public void setPostp(String postp){
         this.postp = postp;
     }

     public String getPostp(){
         return postp;
     }

     public void setPosnr(String posnr){
         this.posnr = posnr;
     }

     public String getPosnr(){
         return posnr;
     }

     public void setXloek(String xloek){
         this.xloek = xloek;
     }

     public String getXloek(){
         return xloek;
     }

     public void setMatnr(String matnr){
         this.matnr = matnr;
     }

     public String getMatnr(){
         return matnr;
     }

     public void setMaktx(String maktx){
         this.maktx = maktx;
     }

     public String getMaktx(){
         return maktx;
     }

     public void setWerks(String werks){
         this.werks = werks;
     }

     public String getWerks(){
         return werks;
     }

     public void setLgort(String lgort){
         this.lgort = lgort;
     }

     public String getLgort(){
         return lgort;
     }

     public void setBdmng(Double bdmng){
         this.bdmng = bdmng;
     }

     public Double getBdmng(){
         return bdmng;
     }

     public void setMeins(String meins){
         this.meins = meins;
     }

     public String getMeins(){
         return meins;
     }

     public void setRgekz(String rgekz){
         this.rgekz = rgekz;
     }

     public String getRgekz(){
         return rgekz;
     }

     public void setAufpl(String aufpl){
         this.aufpl = aufpl;
     }

     public String getAufpl(){
         return aufpl;
     }

     public void setVornr(String vornr){
         this.vornr = vornr;
     }

     public String getVornr(){
         return vornr;
     }

     public void setAplzl(String aplzl){
         this.aplzl = aplzl;
     }

     public String getAplzl(){
         return aplzl;
     }

    @Override
    public Date getCreationDate() {
        return creationDate;
    }

    @Override
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public Date getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }
}
