package yj.core.imfpmimptttemp.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable=true)
@Table(name = "imf_pm_imptt_temp")
public class ImpttTemp extends BaseDTO {
    @Id
    private String mpobj;//设备编号

    private String eqktu;//设备描述

    private String point;//计量点

    private String pttxt;//计量点描述

    private Integer checkseq;//点检顺序号

    private String checkreq;//点检要求

    private String checkcycle;//点检周期

    private String checkde;//点检部门

    private String checkdate;//点检日期

    private String checkshift;//点检班次: 1 白班,2 中班,3 夜班

    private String checkuser;//点检人

    private String checkkey;//是否关键点:Y：关键点，在点检时需拍照留证;N：不是关键点，点检时不需要拍照留证，单如果是点检不合格，则需要拍照留证；默认为N

    private String checkplan;//是否配置点检计划:N 否，表示默认每班点检，默认为N;Y 是，表示必须设置点检计划

    private String mronotice;//是否产生维修通知单:Y：表示在点检不合格时，产生维修通知单;N：表示不产生维修通知单，默认为N

    private String iwerk;//工厂

    private String tplnr;//功能位置

    private String pltxt;//功能位置描述

    private String arbpl;//工作中心

    private String ktext;//工作中心描述

    private String checkobject;//点检类型:C：点检；R：复检

    private Integer checkplanId;//点检计划编号

    private String codct;//目录:常量：Z

    private String codgr;// 代码组

    private String atinn;//内部特性号(特征编号）:该字段需转换，未转换前是10位数字格式

    private Integer decim;//十进制位

    private Float mrmin;//范围下限:这个字段是科学计数，转换为10进制计数后需要除以100

    private Float mrmax;//范围上限:这个字段是科学计数，转换为10进制计数后需要除以100

    private Integer mrngu;//计量范围单位

    public String getMpobj() {
        return mpobj;
    }

    public void setMpobj(String mpobj) {
        this.mpobj = mpobj;
    }

    public String getEqktu() {
        return eqktu;
    }

    public void setEqktu(String eqktu) {
        this.eqktu = eqktu;
    }

    public String getPoint() {
        return point;
    }

    public void setPoint(String point) {
        this.point = point;
    }

    public String getPttxt() {
        return pttxt;
    }

    public void setPttxt(String pttxt) {
        this.pttxt = pttxt;
    }

    public Integer getCheckseq() {
        return checkseq;
    }

    public void setCheckseq(Integer checkseq) {
        this.checkseq = checkseq;
    }

    public String getCheckreq() {
        return checkreq;
    }

    public void setCheckreq(String checkreq) {
        this.checkreq = checkreq;
    }

    public String getCheckcycle() {
        return checkcycle;
    }

    public void setCheckcycle(String checkcycle) {
        this.checkcycle = checkcycle;
    }

    public String getCheckde() {
        return checkde;
    }

    public void setCheckde(String checkde) {
        this.checkde = checkde;
    }

    public String getCheckdate() {
        return checkdate;
    }

    public void setCheckdate(String checkdate) {
        this.checkdate = checkdate;
    }

    public String getCheckshift() {
        return checkshift;
    }

    public void setCheckshift(String checkshift) {
        this.checkshift = checkshift;
    }

    public String getCheckuser() {
        return checkuser;
    }

    public void setCheckuser(String checkuser) {
        this.checkuser = checkuser;
    }

    public String getCheckkey() {
        return checkkey;
    }

    public void setCheckkey(String checkkey) {
        this.checkkey = checkkey;
    }

    public String getCheckplan() {
        return checkplan;
    }

    public void setCheckplan(String checkplan) {
        this.checkplan = checkplan;
    }

    public String getMronotice() {
        return mronotice;
    }

    public void setMronotice(String mronotice) {
        this.mronotice = mronotice;
    }

    public String getIwerk() {
        return iwerk;
    }

    public void setIwerk(String iwerk) {
        this.iwerk = iwerk;
    }

    public String getTplnr() {
        return tplnr;
    }

    public void setTplnr(String tplnr) {
        this.tplnr = tplnr;
    }

    public String getPltxt() {
        return pltxt;
    }

    public void setPltxt(String pltxt) {
        this.pltxt = pltxt;
    }

    public String getArbpl() {
        return arbpl;
    }

    public void setArbpl(String arbpl) {
        this.arbpl = arbpl;
    }

    public String getKtext() {
        return ktext;
    }

    public void setKtext(String ktext) {
        this.ktext = ktext;
    }

    public String getCheckobject() {
        return checkobject;
    }

    public void setCheckobject(String checkobject) {
        this.checkobject = checkobject;
    }

    public Integer getCheckplanId() {
        return checkplanId;
    }

    public void setCheckplanId(Integer checkplanId) {
        this.checkplanId = checkplanId;
    }

    public String getCodct() {
        return codct;
    }

    public void setCodct(String codct) {
        this.codct = codct;
    }

    public String getCodgr() {
        return codgr;
    }

    public void setCodgr(String codgr) {
        this.codgr = codgr;
    }

    public String getAtinn() {
        return atinn;
    }

    public void setAtinn(String atinn) {
        this.atinn = atinn;
    }

    public Integer getDecim() {
        return decim;
    }

    public void setDecim(Integer decim) {
        this.decim = decim;
    }

    public Float getMrmin() {
        return mrmin;
    }

    public void setMrmin(Float mrmin) {
        this.mrmin = mrmin;
    }

    public Float getMrmax() {
        return mrmax;
    }

    public void setMrmax(Float mrmax) {
        this.mrmax = mrmax;
    }

    public Integer getMrngu() {
        return mrngu;
    }

    public void setMrngu(Integer mrngu) {
        this.mrngu = mrngu;
    }
}
