package yj.core.webservice_readbglog.sender;


import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 *
 * <pre>
 * SI_READBGLOG_Sender_SynService service = new SI_READBGLOG_Sender_SynService();
 * SIREADBGLOGSenderSyn portType = service.getHTTPPort();
 * portType.siREADBGLOGSenderSyn(...);
 * </pre>
 *
 * </p>
 *
 */
@WebServiceClient(name = "SI_READBGLOG_Sender_SynService", targetNamespace = "http://www.cq-yj.com/HAP/READBGLOG/Sender", wsdlLocation = "resources/readbglog.xml")
public class SIREADBGLOGSenderSynService extends Service {

    public final static URL WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(SIREADBGLOGSenderSynService.class.getName());

    static {
        URL url = null;
        url = SIREADBGLOGSenderSynService.class.getClassLoader().getResource("readbglog.xml");
        System.out.println(url);
        WSDL_LOCATION = url;
    }

    public SIREADBGLOGSenderSynService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIREADBGLOGSenderSynService() {
        super(WSDL_LOCATION, new QName(
                "http://www.cq-yj.com/HAP/READBGLOG/Sender",
                "SI_READBGLOG_Sender_SynService"));
    }

    /**
     *
     * @return returns SIREADBGLOGSenderSyn
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIREADBGLOGSenderSyn getHTTPPort() {
        return super.getPort(new QName(
                        "http://www.cq-yj.com/HAP/READBGLOG/Sender", "HTTP_Port"),
                SIREADBGLOGSenderSyn.class);
    }

    /**
     *
     * @return returns SIREADBGLOGSenderSyn
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIREADBGLOGSenderSyn getHTTPSPort() {
        return super.getPort(new QName(
                        "http://www.cq-yj.com/HAP/READBGLOG/Sender", "HTTPS_Port"),
                SIREADBGLOGSenderSyn.class);
    }

}

