package yj.core.webservice_readbglog.sender;


import yj.core.webservice_readbglog.receiver.DTREADBGLOGRes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 *
 */
@WebService(name = "SI_READBGLOG_Sender_Syn", targetNamespace = "http://www.cq-yj.com/HAP/READBGLOG/Sender")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIREADBGLOGSenderSyn {

    /**
     *
     * @param mtREADBGLOGReq
     * @return returns com.cq_yj.hap.readbglog.sender.DTREADBGLOGRes
     */
    @WebMethod(operationName = "SI_READBGLOG_Sender_Syn", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_READBGLOG_Res", targetNamespace = "http://www.cq-yj.com/HAP/READBGLOG/Sender", partName = "MT_READBGLOG_Res")
    public DTREADBGLOGRes siREADBGLOGSenderSyn(
            @WebParam(name = "MT_READBGLOG_Req", targetNamespace = "http://www.cq-yj.com/HAP/READBGLOG/Sender", partName = "MT_READBGLOG_Req") DTREADBGLOGReq mtREADBGLOGReq);

}

