package yj.core.outsrgreceipthead.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable=true)
@Table(name = "wip_outsrgreceipthead")
public class Outsrgreceipthead extends BaseDTO {
     @NotEmpty
      private String receiptnm; //外协收货单号

     @Id
     @GeneratedValue
      private String werks; //工厂

      private String lifnr; //供应商编号

      private String matnr; //物料编号

      private String status; //单据状态

      private String zdpdat; //收货过账日期

      private String zdptim; //收货过账时间

      private String zdpuser; //收货过账账号

      private String prtflag; //打印标识

      private String zipdat;

      private String ziptim;

      private String zipuser;

    public void setZdpdat(String zdpdat) {
        this.zdpdat = zdpdat;
    }

    public void setZdptim(String zdptim) {
        this.zdptim = zdptim;
    }

    public String getZipdat() {
        return zipdat;
    }

    public void setZipdat(String zipdat) {
        this.zipdat = zipdat;
    }

    public String getZiptim() {
        return ziptim;
    }

    public void setZiptim(String ziptim) {
        this.ziptim = ziptim;
    }

    public String getZipuser() {
        return zipuser;
    }

    public void setZipuser(String zipuser) {
        this.zipuser = zipuser;
    }

    public void setReceiptnm(String receiptnm){
         this.receiptnm = receiptnm;
     }

     public String getReceiptnm(){
         return receiptnm;
     }

     public void setWerks(String werks){
         this.werks = werks;
     }

     public String getWerks(){
         return werks;
     }

     public void setLifnr(String lifnr){
         this.lifnr = lifnr;
     }

     public String getLifnr(){
         return lifnr;
     }

     public void setMatnr(String matnr){
         this.matnr = matnr;
     }

     public String getMatnr(){
         return matnr;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }


    public String getZdpdat() {
        return zdpdat;
    }

    public String getZdptim() {
        return zdptim;
    }

    public String getZdpuser() {
        return zdpuser;
    }

    public void setZdpuser(String zdpuser) {
        this.zdpuser = zdpuser;
    }

    public void setPrtflag(String prtflag){
         this.prtflag = prtflag;
     }

     public String getPrtflag(){
         return prtflag;
     }

     }
