package yj.core.pmcabn.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable=true)
@Table(name = "sap_pm_cabn")
public class Cabn extends BaseDTO {
    @Id
    private String atinn;//内部特性号(特征编号）:该字段需转换，未转换前是10位数字格式

    private String atbez;//特性描述

    private String atkla;//特征组：常量：ZYJPMC 渝江设备点检特性组

    private String atmst;//特性状态：0 在准备中；1 已发布；2 被锁定；只有状态为1时，才允许正常使用

    private Integer anzst;//字符数

    private Integer anzdz;//小数位

    private Integer msehi;//内部度量单位

    private String aname;//创建者

    private String adatu;//创建日期

    private String vname;//更改者

    private String vdatu;//更改日期

    public String getAtinn() {
        return atinn;
    }

    public void setAtinn(String atinn) {
        this.atinn = atinn;
    }

    public String getAtbez() {
        return atbez;
    }

    public void setAtbez(String atbez) {
        this.atbez = atbez;
    }

    public String getAtkla() {
        return atkla;
    }

    public void setAtkla(String atkla) {
        this.atkla = atkla;
    }

    public String getAtmst() {
        return atmst;
    }

    public void setAtmst(String atmst) {
        this.atmst = atmst;
    }

    public Integer getAnzst() {
        return anzst;
    }

    public void setAnzst(Integer anzst) {
        this.anzst = anzst;
    }

    public Integer getAnzdz() {
        return anzdz;
    }

    public void setAnzdz(Integer anzdz) {
        this.anzdz = anzdz;
    }

    public Integer getMsehi() {
        return msehi;
    }

    public void setMsehi(Integer msehi) {
        this.msehi = msehi;
    }

    public String getAname() {
        return aname;
    }

    public void setAname(String aname) {
        this.aname = aname;
    }

    public String getAdatu() {
        return adatu;
    }

    public void setAdatu(String adatu) {
        this.adatu = adatu;
    }

    public String getVname() {
        return vname;
    }

    public void setVname(String vname) {
        this.vname = vname;
    }

    public String getVdatu() {
        return vdatu;
    }

    public void setVdatu(String vdatu) {
        this.vdatu = vdatu;
    }
}
