package yj.core.webservice_createtp.sender;

/**
 * Created by 917110140 on 2018/9/20.
 */
import yj.core.webservice_createtp.receiver.DTCREATPRes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 *
 */
@WebService(name = "SI_CREATP_Sender_Syn", targetNamespace = "http://www.cq-yj.com/HAP/CREATP/Sender")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SICREATPSenderSyn {

    /**
     *
     * @param mtCREATPReq
     * @return returns com.cq_yj.hap.creatp.sender.DTCREATPRes
     */
    @WebMethod(operationName = "SI_CREATP_Sender_Syn", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_CREATP_Res", targetNamespace = "http://www.cq-yj.com/HAP/CREATP/Sender", partName = "MT_CREATP_Res")
    public DTCREATPRes siCREATPSenderSyn(
            @WebParam(name = "MT_CREATP_Req", targetNamespace = "http://www.cq-yj.com/HAP/CREATP/Sender", partName = "MT_CREATP_Req") DTCREATPReq mtCREATPReq);

}
