package yj.core.webservice_createtp.sender;

/**
 * Created by 917110140 on 2018/9/20.
 */

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 *
 * <pre>
 * SI_CREATP_Sender_SynService service = new SI_CREATP_Sender_SynService();
 * SICREATPSenderSyn portType = service.getHTTPPort();
 * portType.siCREATPSenderSyn(...);
 * </pre>
 *
 * </p>
 *
 */
@WebServiceClient(name = "SI_CREATP_Sender_SynService", targetNamespace = "http://www.cq-yj.com/HAP/CREATP/Sender", wsdlLocation = "resources/createTp.xml")
public class SICREATPSenderSynService extends Service {

    public final static URL WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(SICREATPSenderSynService.class.getName());

    static {
        URL url = null;
        url = SICREATPSenderSynService.class.getClassLoader().getResource("createTp.xml");
        System.out.println(url);
        WSDL_LOCATION = url;
    }

    public SICREATPSenderSynService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SICREATPSenderSynService() {
        super(WSDL_LOCATION, new QName(
                "http://www.cq-yj.com/HAP/CREATP/Sender",
                "SI_CREATP_Sender_SynService"));
    }

    /**
     *
     * @return returns SICREATPSenderSyn
     */
    @WebEndpoint(name = "HTTP_Port")
    public SICREATPSenderSyn getHTTPPort() {
        return super.getPort(new QName(
                        "http://www.cq-yj.com/HAP/CREATP/Sender", "HTTP_Port"),
                SICREATPSenderSyn.class);
    }

    /**
     *
     * @return returns SICREATPSenderSyn
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SICREATPSenderSyn getHTTPSPort() {
        return super.getPort(new QName(
                        "http://www.cq-yj.com/HAP/CREATP/Sender", "HTTPS_Port"),
                SICREATPSenderSyn.class);
    }

}

