package yj.core.webservice.sender;

import yj.core.webservice.receiver.DTPP001SendRes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SI_PP001_Sender_Sync", targetNamespace = "http://www.cq-yj.com/HAP/PP001/Sender")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIPP001SenderSync {

	/**
	 * 
	 * @param mtPP001SendReq
	 * @return returns com.cq_yj.hap.pp001.sender.DTPP001SendRes
	 */
	@WebMethod(operationName = "SI_PP001_Sender_Sync", action = "http://sap.com/xi/WebService/soap1.1")
	@WebResult(name = "MT_PP001_Send_Res", targetNamespace = "http://www.cq-yj.com/HAP/PP001/Receiver", partName = "MT_PP001_Send_Res")
	public DTPP001SendRes siPP001SenderSync(
            @WebParam(name = "MT_PP001_Send_Req", targetNamespace = "http://www.cq-yj.com/HAP/PP001/Receiver", partName = "MT_PP001_Send_Req") DTPP001SendReq mtPP001SendReq);

}
