package yj.core.outsrgissuehead.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable=true)
@Table(name = "wip_outsrgissuehead")
public class Outsrgissuehead extends BaseDTO {
     @NotEmpty
      private String issuenm; //外协发料单号

     @Id
     @GeneratedValue
      private String werks; //工厂

      private String txz01; //工序说明

      private String lifnr; //供应商编号

      private String matnr; //物料编号

      private String status; //单据状态

      private String prtflag; //打印标识

    private String zipuser;//单据打印账号

    private String zipdat; //单据打印日期

    private String ziptim; //单据打印时间

    public String getZipuser() {
        return zipuser;
    }

    public void setZipuser(String zipuser) {
        this.zipuser = zipuser;
    }

    public String getZipdat() {
        return zipdat;
    }

    public void setZipdat(String zipdat) {
        this.zipdat = zipdat;
    }

    public String getZiptim() {
        return ziptim;
    }

    public void setZiptim(String ziptim) {
        this.ziptim = ziptim;
    }

    public void setIssuenm(String issuenm){
         this.issuenm = issuenm;
     }

     public String getIssuenm(){
         return issuenm;
     }

     public void setWerks(String werks){
         this.werks = werks;
     }

     public String getWerks(){
         return werks;
     }

     public void setTxz01(String txz01){
         this.txz01 = txz01;
     }

     public String getTxz01(){
         return txz01;
     }

     public void setLifnr(String lifnr){
         this.lifnr = lifnr;
     }

     public String getLifnr(){
         return lifnr;
     }

     public void setMatnr(String matnr){
         this.matnr = matnr;
     }

     public String getMatnr(){
         return matnr;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     public void setPrtflag(String prtflag){
         this.prtflag = prtflag;
     }

     public String getPrtflag(){
         return prtflag;
     }

     }
