package yj.core.imfpmcheckplan.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable=true)
@Table(name = "imf_pm_checkplan")
public class Checkplan extends BaseDTO {
    @Id
    private String mpobj;//设备编号
    @Id
    private String point;//计量点

    private String pttxt;//计量点描述

    private String checkrequest;//点检要求

    private String checkcycle;//点检周期

    private String checkde;//点检部门

    private String iwerk;//工厂

    private String tplnr;//功能位置

    private String pltxt;//功能位置描述

    private String arbpl;//工作中心

    private String ktext;//工作中心描述
    @Id
    @GeneratedValue
    private Integer checkplanId;//点检计划编号

    private String executeFlag;//点检计划执行标志：N：未执行点检;Y：已执行点检

    private String checkdate;//点检日期

    private String checkshift;//点检班次

    private String crdate;//创建日期

    private String crtime;//创建时间

    private String cruser;//创建人员

    private String deleteFlag;//删除标识：逻辑删除；如果被删除了，则打上X标识

    private String chdate;//修改日期

    private String chtime;//修改时间

    private String chuser;//修改人员

    public String getMpobj() {
        return mpobj;
    }

    public void setMpobj(String mpobj) {
        this.mpobj = mpobj;
    }

    public String getPoint() {
        return point;
    }

    public void setPoint(String point) {
        this.point = point;
    }

    public String getPttxt() {
        return pttxt;
    }

    public void setPttxt(String pttxt) {
        this.pttxt = pttxt;
    }

    public String getCheckrequest() {
        return checkrequest;
    }

    public void setCheckrequest(String checkrequest) {
        this.checkrequest = checkrequest;
    }

    public String getCheckcycle() {
        return checkcycle;
    }

    public void setCheckcycle(String checkcycle) {
        this.checkcycle = checkcycle;
    }

    public String getCheckde() {
        return checkde;
    }

    public void setCheckde(String checkde) {
        this.checkde = checkde;
    }

    public String getIwerk() {
        return iwerk;
    }

    public void setIwerk(String iwerk) {
        this.iwerk = iwerk;
    }

    public String getTplnr() {
        return tplnr;
    }

    public void setTplnr(String tplnr) {
        this.tplnr = tplnr;
    }

    public String getPltxt() {
        return pltxt;
    }

    public void setPltxt(String pltxt) {
        this.pltxt = pltxt;
    }

    public String getArbpl() {
        return arbpl;
    }

    public void setArbpl(String arbpl) {
        this.arbpl = arbpl;
    }

    public String getKtext() {
        return ktext;
    }

    public void setKtext(String ktext) {
        this.ktext = ktext;
    }

    public Integer getCheckplanId() {
        return checkplanId;
    }

    public void setCheckplanId(Integer checkplanId) {
        this.checkplanId = checkplanId;
    }

    public String getExecuteFlag() {
        return executeFlag;
    }

    public void setExecuteFlag(String executeFlag) {
        this.executeFlag = executeFlag;
    }

    public String getCheckdate() {
        return checkdate;
    }

    public void setCheckdate(String checkdate) {
        this.checkdate = checkdate;
    }

    public String getCheckshift() {
        return checkshift;
    }

    public void setCheckshift(String checkshift) {
        this.checkshift = checkshift;
    }

    public String getCrdate() {
        return crdate;
    }

    public void setCrdate(String crdate) {
        this.crdate = crdate;
    }

    public String getCrtime() {
        return crtime;
    }

    public void setCrtime(String crtime) {
        this.crtime = crtime;
    }

    public String getCruser() {
        return cruser;
    }

    public void setCruser(String cruser) {
        this.cruser = cruser;
    }

    public String getDeleteFlag() {
        return deleteFlag;
    }

    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    public String getChdate() {
        return chdate;
    }

    public void setChdate(String chdate) {
        this.chdate = chdate;
    }

    public String getChtime() {
        return chtime;
    }

    public void setChtime(String chtime) {
        this.chtime = chtime;
    }

    public String getChuser() {
        return chuser;
    }

    public void setChuser(String chuser) {
        this.chuser = chuser;
    }
}
