package yj.core.qjcode.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable=true)
@Table(name = "wip_qjcode")
public class Qjcode extends BaseDTO {
     @Id
     @GeneratedValue
      private Long id; //序号

     @NotEmpty
      private String rcode; //取件原因

      private String sld1;

      private String sld2;

      private  Long sortnum;//排序码

     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setRcode(String rcode){
         this.rcode = rcode;
     }

     public String getRcode(){
         return rcode;
     }

    public String getSld1() {
        return sld1;
    }

    public void setSld1(String sld1) {
        this.sld1 = sld1;
    }

    public Long getSortnum() {
        return sortnum;
    }

    public void setSortnum(Long sortnum) {
        this.sortnum = sortnum;
    }

    public String getSld2() {
        return sld2;
    }

    public void setSld2(String sld2) {
        this.sld2 = sld2;
    }
}
