package yj.core.webservice_queryoldzpgdbar.sender;

import yj.core.webservice_queryoldzpgdbar.receiver.DTQUERYOLDZPGDBARSendRes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 *
 */
@WebService(name = "SI_QUERYOLDZPGDBAR_Sender_Sync", targetNamespace = "http://www.cq-yj.com/HAP/QueryOldZpgdbar/Sender")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIQUERYOLDZPGDBARSenderSync {

    /**
     *
     * @param mtQUERYOLDZPGDBARSendReq
     * @return returns
     *         com.cq_yj.hap.queryoldzpgdbar.sender.DTQUERYOLDZPGDBARSendRes
     */
    @WebMethod(operationName = "SI_QUERYOLDZPGDBAR_Sender_Sync", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_QUERYOLDZPGDBAR_Send_Res", targetNamespace = "http://www.cq-yj.com/HAP/QueryOldZpgdbar/Sender", partName = "MT_QUERYOLDZPGDBAR_Send_Res")
    public DTQUERYOLDZPGDBARSendRes siQUERYOLDZPGDBARSenderSync(
            @WebParam(name = "MT_QUERYOLDZPGDBAR_Send_Req", targetNamespace = "http://www.cq-yj.com/HAP/QueryOldZpgdbar/Sender", partName = "MT_QUERYOLDZPGDBAR_Send_Req") DTQUERYOLDZPGDBARSendReq mtQUERYOLDZPGDBARSendReq);

}
