package yj.core.webservice_queryoldzpgdbar.sender;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 *
 * <pre>
 * SI_QUERYOLDZPGDBAR_Sender_SyncService service = new SI_QUERYOLDZPGDBAR_Sender_SyncService();
 * SIQUERYOLDZPGDBARSenderSync portType = service.getHTTPPort();
 * portType.siQUERYOLDZPGDBARSenderSync(...);
 * </pre>
 *
 * </p>
 *
 */
@WebServiceClient(name = "SI_QUERYOLDZPGDBAR_Sender_SyncService", targetNamespace = "http://www.cq-yj.com/HAP/QueryOldZpgdbar/Sender", wsdlLocation = "resources/queryoldzpgdbar.xml")
public class SIQUERYOLDZPGDBARSenderSyncService extends Service {

    public final static URL WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(SIQUERYOLDZPGDBARSenderSyncService.class.getName());

    static {
        URL url = null;
        url = SIQUERYOLDZPGDBARSenderSyncService.class.getClassLoader().getResource("queryoldzpgdbar.xml");
        System.out.println(url);
        WSDL_LOCATION = url;
    }

    public SIQUERYOLDZPGDBARSenderSyncService(URL wsdlLocation,
                                              QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIQUERYOLDZPGDBARSenderSyncService() {
        super(WSDL_LOCATION, new QName(
                "http://www.cq-yj.com/HAP/QueryOldZpgdbar/Sender",
                "SI_QUERYOLDZPGDBAR_Sender_SyncService"));
    }

    /**
     *
     * @return returns SIQUERYOLDZPGDBARSenderSync
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIQUERYOLDZPGDBARSenderSync getHTTPPort() {
        return super.getPort(
                new QName("http://www.cq-yj.com/HAP/QueryOldZpgdbar/Sender",
                        "HTTP_Port"), SIQUERYOLDZPGDBARSenderSync.class);
    }

    /**
     *
     * @return returns SIQUERYOLDZPGDBARSenderSync
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIQUERYOLDZPGDBARSenderSync getHTTPSPort() {
        return super.getPort(
                new QName("http://www.cq-yj.com/HAP/QueryOldZpgdbar/Sender",
                        "HTTPS_Port"), SIQUERYOLDZPGDBARSenderSync.class);
    }

}

