package yj.core.cust.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable=true)
@Table(name = "sap_cust")
public class Cust extends BaseDTO {
     @Id
     @GeneratedValue
      private String mandt; //集团

     @NotEmpty
      private String kunnr; //客户代码

      private String name1; //客户名称1

      private String sortl; //客户简称


     public void setMandt(String mandt){
         this.mandt = mandt;
     }

     public String getMandt(){
         return mandt;
     }

     public void setKunnr(String kunnr){
         this.kunnr = kunnr;
     }

     public String getKunnr(){
         return kunnr;
     }

     public void setName1(String name1){
         this.name1 = name1;
     }

     public String getName1(){
         return name1;
     }

     public void setSortl(String sortl){
         this.sortl = sortl;
     }

     public String getSortl(){
         return sortl;
     }

     }
