package yj.core.webserver_outsrgreceipt.sender;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 *
 * <pre>
 * SI_OUTSRGRECEIPT_Sender_SyncService service = new SI_OUTSRGRECEIPT_Sender_SyncService();
 * SIOUTSRGRECEIPTSenderSync portType = service.getHTTPPort();
 * portType.siOUTSRGRECEIPTSenderSync(...);
 * </pre>
 *
 * </p>
 *
 */
@WebServiceClient(name = "SI_OUTSRGRECEIPT_Sender_SyncService", targetNamespace = "http://www.cq-yj.com/HAP/OUTSRGRECEIPT/Sender", wsdlLocation = "resources/outsrgreceipt.xml")
public class SIOUTSRGRECEIPTSenderSyncService extends Service {

    public final static URL WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(SIOUTSRGRECEIPTSenderSyncService.class.getName());

    static {
        URL url = null;
        url = SIOUTSRGRECEIPTSenderSyncService.class.getClassLoader().getResource("outsrgreceipt.xml");
        System.out.println(url);
        WSDL_LOCATION = url;
    }

    public SIOUTSRGRECEIPTSenderSyncService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIOUTSRGRECEIPTSenderSyncService() {
        super(WSDL_LOCATION, new QName(
                "http://www.cq-yj.com/HAP/OUTSRGRECEIPT/Sender",
                "SI_OUTSRGRECEIPT_Sender_SyncService"));
    }

    /**
     *
     * @return returns SIOUTSRGRECEIPTSenderSync
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIOUTSRGRECEIPTSenderSync getHTTPPort() {
        return super.getPort(new QName(
                        "http://www.cq-yj.com/HAP/OUTSRGRECEIPT/Sender", "HTTP_Port"),
                SIOUTSRGRECEIPTSenderSync.class);
    }

    /**
     *
     * @return returns SIOUTSRGRECEIPTSenderSync
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIOUTSRGRECEIPTSenderSync getHTTPSPort() {
        return super.getPort(new QName(
                        "http://www.cq-yj.com/HAP/OUTSRGRECEIPT/Sender", "HTTPS_Port"),
                SIOUTSRGRECEIPTSenderSync.class);
    }

}

